### ISSUE TITLE
[Tchap Annonces] Améliorer la présentation

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#1000]
Les messages Tchap-Annonces / Tchap-Infos apparaissent dans une section à part en fin de liste des salons.

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/e3e19a60-5c21-4971-a6e7-9f8e64e08a21)

Renommer la section de "Alertes système" -> "Tchap Annonces".

Il ne semble pas nécessaire de les mettre dans une section.

Il serait bien de les remonter en tête de tous les salons quand un message non-lu est dedans,

**Comment by NicolasBuquet** [comment]
Modification du titre de section 'Alertes système" -> "Tchap Annonces"

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/02d13175-5786-4caa-b9f1-ce7523df6f3b)

**Comment by NicolasBuquet** [comment]
@areox-net @odelcroi 

Prend-on la décision : 
- que l'on n'aura qu'un seul et unique canal d'annonce
- et qu'à ce titre, on peut présenter les Tchap Annonces comme un salon classique (pas de section avec scroll horizontal possible)
?

**Comment by areox-net** [comment]
@NicolasBuquet Pour ce qui me concerne oui. Je trouve perturbant le fait d'ajouter un bandeau que pour ça. Ca fait perdre beaucoup de place aux autres conversations.

**Comment by NicolasBuquet** [comment]
C'est fait ! @areox-net  @odelcroi 

Et ça doit conserver le multi-channel "Server Notices" si besoin et ça doit gérer les channels comme les rooms classiques (tri, favoris, notifs, ordre d'affichage en fonction des non-lus…)

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/bc52ef09-4236-4616-bd44-bb8991a7c0cc)

**Comment by areox-net** [comment]
@NicolasBuquet Cool. 
J'ai vu que sur Element X sont reapparus les filtres sur la liste des conversations. Ils ont l'air plus flexible, avec la selection multiple possible.

![image](https://github.com/tchapgouv/tchap-ios/assets/1255251/206d97ae-ffdf-46e9-8d3c-4eddef65738f)
