### ISSUE TITLE
Conversations list: display the barred bell for muted room

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#101]
Display the barred bell for muted room
![tchap_ic_notification_mute_bell](https://user-images.githubusercontent.com/8969772/47920521-831c1200-deb2-11e8-9a75-4f8b709c1aa2.png)

Presently only 2 levels of notification mode is supported in ios: "all messages" and "mention only".
The "mute" mode is not available.
This point need to be defined.

**Comment by NicolasBuquet** [comment]
Done in Tchap 2.6.2 (don't know when).

Close.
