### ISSUE TITLE
Notification email : améliorer la compréhension du fonctionnement de la feature

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#1029]
Ajouter une ligne d'explication sous le bouton d'activation des notifications email dans les paramètres.

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/796e7583-d685-49ba-94ff-2f4606962e41)

**Comment by odelcroi** [comment]
Could you update the FAQ with the "how to configure" ? 
https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/helpdesk/articles/fr/305e2d06-22eb-4e33-9602-c6ddf82f4774/
@NicolasBuquet

**Comment by NicolasBuquet** [comment]
@odelcroi Done
