### ISSUE TITLE
Partage de géolocalisation : créer les pages FAQ

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#1038]
Le partage de géolocalisation (en temps réel ou non) va bientôt être déployé.

il faut créer une page de FAQ par plateforme pour expliquer aux utilisateurs : 
- où trouver la fonctionnalité
- comment paramétrer les autorisations pour autoriser la fonctionnalité

**Comment by Nivann** [comment]
Titre : Comment partager sa position dans Tchap ?

**Comment by NicolasBuquet** [comment]
Version iOS draft faite : https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/helpdesk/articles/fr/9ec1095c-dec4-495d-a6d4-742f5a58102f/

**Comment by NicolasBuquet** [comment]
Done
https://aide.tchap.beta.gouv.fr/fr/article/partagez-votre-position-geographique-avec-tchap-1rzpx24/
