### ISSUE TITLE
Probleme de pillule de lien de salon qui n'apparait pas

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-ios#1049]
### Steps to reproduce
Dans un forum 

![ima_582a8d5](https://github.com/tchapgouv/tchap-ios/assets/4077729/67ebdfc5-c9db-4944-97b0-2bbecc72f999)

### Your phone model

iPhone X

### Operating system version

iOS 16.7.8

### Will you send logs?

Yes

**Comment by NicolasBuquet** [comment]
Autre exemple de mise en page problématique sur iOS (dans le forum beta-testeurs iOS).

Le même message s'affiche de manière incomplète sur iOS et de manière complète sur NEO.

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/92de7c6b-8c29-448c-a94c-58ca50bc3371)

Problème lié aux Pills ?

**Comment by NicolasBuquet** [comment]
Et sur un même salon iOS, parfois les liens de salon s'affichent en Pill et parfois non.

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/0b99440d-fc66-4a8d-9ca3-8a43ff04d799)

Il faut trouver pourquoi.
