### ISSUE TITLE
Report a content doesn't seems work

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#1060]
No error is displayed on web but the error is not reported.

See investigation on web issue : https://github.com/tchapgouv/tchap-web-v4/issues/1038

**Comment by NicolasBuquet** [comment]
Sur iOS, l'appel suivant a lieu : 
```
[MXHTTPClient] #32 - POST _matrix/client/r0/rooms/!GYvvtLxkvYfjqEMPKE:agent.dinum.tchap.gouv.fr/report/%24opyKuMd-KhvSwW0qJPrpTNZ8ik_GCCX5jUlatErFEQg completed in 91ms
```

et la réponse du back-end est SUCCESS.

Le problème serait donc bien un souci côté back-end plutôt que côté client.

**Comment by MarcWadai** [comment]
fixed by https://github.com/tchapgouv/tchap-infra/issues/2892
