### ISSUE TITLE
Ajouter une description sous les notifications de compte

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-ios#1091]
L'utilisateur peut être perdu entre les notifications de compte et d'appareil.
Pour l'aider dans sa compréhension, on pourrait ajouter une description en dessous des notifications de compte. Une définition de compte :
"Le compte correspond à tous vos appareils connectés à Tchap."

On pourrait également ajouter "uniquement" aux notifs appareil : Activer les notifications pour cet appareil uniquement
Cela rend encore plus clair la distinction pour l'utilisateur.

**Comment by NicolasBuquet** [comment]
@Delphgateau Le réglage global pour le compte ne semble pas être présent sur iOS.

- web : 
<img width="681" alt="Screenshot 2024-09-30 at 11 48 35" src="https://github.com/user-attachments/assets/2dc1be91-b0ae-434d-b367-5ddbac5ce0b3">

- ios 
<img width="383" alt="Screenshot 2024-09-30 at 11 49 57" src="https://github.com/user-attachments/assets/7e2a2eea-b772-4565-845d-20605189a050">

**Comment by Delphgateau** [comment]
@NicolasBuquet ok dans ce cas c'est clair.
On pourrait juste ajouter sous l'explication "Sans cette autorisation, les messages et appels entrants ne seront pas notifiés" 
On a l'impression que ça concerne que les appels
