### ISSUE TITLE
Faciliter l'accès à l'aide sur la vérification d'appareil

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-ios#1105]
Ticket produit lié : https://github.com/tchapgouv/tchap-product/issues/402

Ajouter un bouton "aide" à côté du bouton "vérifier" dans la pop qui s'affiche, qui amène vers la page de la FAQ qui détaille la procédure.

![image](https://github.com/user-attachments/assets/3218367f-929a-4998-81f2-8d67303f8dfc)

**Comment by NicolasBuquet** [comment]
@Delphgateau : Il me semble que cet écran n'est plus jamais affiché sur iOS. (as-tu un protocole de test qui te mène à cet écran ?)

C'est celui-ci maintenant : 

![Image](https://github.com/user-attachments/assets/c814b50d-769c-4bc6-8087-3d316c6353cb)

Il faudrait donc ajouter une ligne-bouton sous le bouton pour accéder à l'aide.

**Comment by Delphgateau** [comment]
En effet sur la 2.8.2 j'ai l'écran que tu as mis :)

**Comment by NicolasBuquet** [comment]
@Delphgateau 

Voici ce que cela donne : 

![Image](https://github.com/user-attachments/assets/f1743bd3-63c5-4eec-9fd8-5ea8565a1d64)
