### ISSUE TITLE
Invite contacts by email

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#141]
- [ ] Add at the top of the contacts list a button with the following label: « inviter des contacts dans Tchap »(see https://zpl.io/2vlxKXn)
- [ ] When the user selects this button, a new screen “Inviter des contacts” is opened (see  https://zpl.io/VDOejMw)
- [ ] This new screen lists all the local contacts who are not tchap users.
- [ ] The multi selection is enabled
- [ ] When the user presses “Inviter”, a direct chat is created for each email, by inviting it.
- [ ] The user is able to fill some email addresses by using the button “Inviter par email” displayed at the top of the list.
- [ ] Notify the user for each invite failure, and sum up the successful invites (https://zpl.io/VDO6zrw).
- [ ] The resulting rooms are hidden from the conversations until the invited contact joined the room.

(See  dinsic-pim/tchap-android#173,  dinsic-pim/tchap-android#174 and  dinsic-pim/tchap-android#175)

- [ ] Check whether an account is already known for the provided email (dinsic-pim/tchap-android#250)
- [ ] Notify user when the contact is not reachable by Tchap (dinsic-pim/tchap-android#184)

**Comment by NicolasBuquet** [comment]
Too old.
