### ISSUE TITLE
Configure per-room retention period for messages

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#239]
Let the room admins determine how long data should be stored for a room.

- The default retention period is 12 months, this is the maximum period. The minimum period is 1 day.
- Only the room admin can change this parameter.
- The expired messages must be removed from the client cache.
- Retention is only considered for non-state events.

see details matrix-org/matrix-dinsic#337

**Comment by giomfo** [comment]
enabled only on Btchap

**Comment by NicolasBuquet** [comment]
La gestion de la rétention a été suspendue sur Tchap pour cause d'instabilité :

https://github.com/matrix-org/synapse/issues/13476
