### ISSUE TITLE
Allow email address with apostrophe to register

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#258]
Presently this kind of email is considered invalid

**Comment by elsa-ssg** [comment]
Some users have "-1" in their email address and this prevents them from receiving the validation email too

**Comment by giomfo** [comment]
The current regex used to check email addresses is available here: https://github.com/matrix-org/matrix-ios-sdk/blob/b1d7dda3378a23aaa42678ee0cea86afada6e2c0/MatrixSDK/Utils/MXTools.m#L27

Emais with apostrophe are considered as invalid, but nothing seems block email with "-1"

**Comment by giomfo** [comment]
We decided to suspend the work on this.
We have to study the potential risks before supporting apostrophe (and other specific symbols) in the email addresses. This will be consider with a low Priority

**Comment by giomfo** [comment]
The first step will be to test account creation on Element-web, then on Element-iOS by allowing ' in the existing regex (defined in the matrix-ios-sdk)

**Comment by NicolasBuquet** [comment]
Will be fixed by https://github.com/matrix-org/matrix-ios-sdk/pull/1826
