### ISSUE TITLE
Private rooms: turn on the option to join on room’s link

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#293]
We named "Private rooms" all the room which are not listed in the rooms directory.
Currently these rooms can be joined only on invite.

DINUM wants to enable the option to join them thanks to a room link (= room alias).

This change requires some designs:
- Should we handle this option during the room creation? or just handle it from the room settings screen?
- How to define the room alias (#foo:<hostname>)? Do we want to let the room admin edit it or we auto-generate it (from the room name)? Do we allow several alias or only one?

**Comment by giomfo** [comment]
This feature require #323

**Comment by giomfo** [comment]
Ready to go on Prod (Enabled only on Preprod: Btchap for the moment)

**Comment by NicolasBuquet** [comment]
Merged in https://github.com/tchapgouv/tchap-ios/pull/324
