### ISSUE TITLE
Public rooms: turn on the option to join only on invite

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#294]
We named "Public rooms" all the rooms listed in the rooms directories.
They are currently joinable without invite from their preview.

DINUM wants to introduce a new access mode for the Public rooms. For some of them, the user will have to ask access to the room admin(s) (= knock mode).

This change requires some designs. Here are the opening questions:
- Shall we limit the room history to the room members? (Prevent others from previewing the room)
- How does the user contact the room admin(s)? by using a direct chat (DM) or a "knock" event?

Note: This request corresponds to the knock mode under discussion in the matrix spec (see [MSC2403: Add "knock" feature](https://github.com/matrix-org/matrix-doc/pull/2403)). Implementation is in progress.

**Comment by NicolasBuquet** [comment]
Un Forum (Public room) est maintenant accessible à tout le monde sans invitation.

Par contre, un Forum peut être limité à l'instance sur laquelle il est hébergé. Il n;est alors pas visible pour les autres instances et donc les domaines hébergés sur les autres instances.
