### ISSUE TITLE
Support deletion of a room

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#295]
Presently the user is able to leave the room to make it disappear from his room list, but the Tchap users request to be able to delete/remove totally a room.

We consider this option would be available only for the room administrator.

This change requires some designs:
- Can we suggest to delete the room when a room admin wants to leave a room? (maybe when he is the last admin)
- Where should we present this option to delete a room? in the room settings when the user is a room admin? 
- Until a new Client-Server API is available, we suggest handling this on client side (for the rooms where the user is the only admin). We will kick all the members before leaving the room and forgetting it.

**Comment by NicolasBuquet** [comment]
Not planned anymore.

A room is naturally forgotten when all members leave.
