### ISSUE TITLE
Update the dialog displayed before the last admin leaves

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#340]
Currently when the last admin wants to leave, they are notified by:
![image](https://user-images.githubusercontent.com/8969772/98484625-3726a500-2211-11eb-9a0f-14212e58e8a2.png)

The suggested design is:
![image](https://user-images.githubusercontent.com/8969772/98484547-99cb7100-2210-11eb-8bd7-a00846b478f5.png)
followed by:
![image](https://user-images.githubusercontent.com/8969772/98484657-54f40a00-2211-11eb-8685-74580fceaf64.png)

I suggest keeping display only one dialog:
title: "Vous êtes le dernier administrateur !"
message: "Ce salon ne pourra pas continuer à exister sans un administrateur. Il sera alors figé, en étant consultable uniquement par ses actuels membres, aucun nouveau message ne pourra être posté. Pour en assurer la survie vous pouvez définir un nouvel administrateur."
option1: "Définir un nouvel administrateur"  -> redirige l'utilisateur sur la liste des membres
option2: "Quitter le salon"   -> sort l'utilisateur du salon sans aucune autre alerte
option3: "Annuler"

**Comment by harellano20** [comment]
Je propose:
title: "Vous êtes le dernier administrateur !"
message: "Ce salon sans un administrateur ne peut plus fonctionner normalement. Il sera alors figé, en étant consultable uniquement par ses actuels membres, aucun nouveau message ne pourra être posté. Pour en assurer la survie vous devez définir un nouvel administrateur."
option1: "Définir un nouvel administrateur" -> redirige l'utilisateur sur la liste des membres
option2: "Quitter le salon" -> sort l'utilisateur du salon sans aucune autre alerte
option3: "Annuler"

**Comment by NicolasBuquet** [comment]
Géré désormais par le module `last_admin` côté back-end : https://github.com/tchapgouv/synapse-manage-last-admin
