### ISSUE TITLE
Display correctly the frozen rooms

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#341]
When the last admin left the room, the existing members can read the room history, but they cannot send new messages: the room is frozen

The suggested design is:
![image](https://user-images.githubusercontent.com/8969772/98485092-29265380-2214-11eb-8309-c4364ce710dc.png)

3 remarks:
- this panel should be displayed when the power level to send a message is <= 0, and there is no administrator
- the button "Créer un nouveau salon avec ces membres" should be renamed "Recréer un salon avec les même membres"
- this button should be hidden until the option is actually available

**Comment by giomfo** [comment]
In case of an external user, the button is always hidden:
![image](https://user-images.githubusercontent.com/8969772/98485428-8de2ad80-2216-11eb-8888-d90da939e93f.png)

**Comment by NicolasBuquet** [comment]
Version actuelle dans Tchap 2.7.8 : 
![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/c4e9e2af-82bc-44bd-a9a5-683f1ef1cf61)
