### ISSUE TITLE
Keys export is not available on iPad iOS 14.2

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#345]
On iPad iOS 14.2, this is not possible to export the keys from the settings, the dialog is not visible:

![image](https://user-images.githubusercontent.com/8969772/99537921-8bb5e700-29ac-11eb-8392-c21dcc4e03ab.png)

To reproduce:
1- Go to Tchap settings
2- Press "Export keys"
3- the dialog is not visible NOK

**Comment by NicolasBuquet** [comment]
Key export was removed in Tchap iOS v2+
