### ISSUE TITLE
Remove the padlock from the avatar of the directs (discussions)

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#371]
DINUM requests to remove the padlock on the avatar of the direct:
- in the list of the rooms
- in the header of the direct chat

**Comment by NicolasBuquet** [comment]
@estellecomment En 2021, la DINUM semble avoir demandé qu'on enlève l'icone de cadenas sur les DM.

**Comment by estellecomment** [comment]
Sur web il n'y en pas sur les DM. Seulement sur les 3 types de rooms.

**Comment by NicolasBuquet** [comment]
The padlock is not present in the list of rooms or in the header of the direct chat for DM as of 2024.04.04.
