### ISSUE TITLE
The room header view layout is wrong since the rebase

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#393]
I observed on the branch used for the current rebase (see #392) the following regression in the room header layout:

![image](https://user-images.githubusercontent.com/8969772/129383948-10c86158-65d4-4dd8-8027-a57845ac3b3e.png)

We will have to discuss a plan to restore this header ([code](https://github.com/tchapgouv/tchap-ios/blob/develop/Tchap/Modules/Room/Views/Title)).
This may be perform during our work to base again Tchap room view controller to the Element one

**Comment by giomfo** [comment]
blocked because I have to plan the rework on the room view controller

**Comment by NicolasBuquet** [comment]
No more a subject. Close.
