### ISSUE TITLE
[Rooms list] the icons of the swipe menu are not visible

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#418]
Since we use the Theme service, the swipe menu is not displayed correctly
![image](https://user-images.githubusercontent.com/8969772/140298322-f1babab2-625d-477c-967a-a51e77cf8204.png)

It was displayed like this previously:
![image](https://user-images.githubusercontent.com/8969772/140298447-e08dfea0-f4db-40ff-9e09-3b9093370abf.png)

The concerned icons are available in the Figma project (v1)

**Comment by NicolasBuquet** [comment]
Fixed
