### ISSUE TITLE
Move back the Element assets under the Riot folder

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#422]
The Tchap [assets](https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets) have been copied from the Element(Riot) assets.

We want here to mode back these assets to the Riot folder, and keep in Tchap folder only the customized ones.

Note: 
- you will have updated https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Home/RoomContextualMenu content during #418 

- some assets have been added by Tchap developers (We should keep them in Tchap/Assets):
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Contacts
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Home/icon_page_favoris.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/LaunchScreen.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/Antivirus
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/ContextMenu/room_context_menu_fav.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/ContextMenu/room_context_menu_share.imageset (I don't think this one is still used in Tchap-ios, keep it only if it is used somewhere)
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/Types
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/Header

- some assets have been updated to applied Tchap color/design. Please try to use the Element ones and apply the Tchap color at the runtime if this is need:
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Common/create_room.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Common/placeholder.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Common/remove_icon.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Common/selection_tick.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Common/selection_untick.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/MediaPicker/camera_capture.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/MediaPicker/camera_video_capture.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/Activities/typing.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/add_participant.imageset
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Room/Input
   - https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Search
   - https://github.com/vector-im/element-ios/tree/develop/Riot/Assets/Images.xcassets/Settings/settings_icon.imageset
   -

**Comment by phlniji** [comment]
Due to their content, those images remains unchanged in the PR :
- https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Common/create_room.imageset
- https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/MediaPicker/camera_capture.imageset
- https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Search (except https://github.com/tchapgouv/tchap-ios/tree/develop/Tchap/Assets/Images.xcassets/Search/search_icon.imageset )
