### ISSUE TITLE
[Room timeline] refresh the RoomViewController with the Element one

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#440]
We want here to use the current RoomViewController module of the Element application. 
This view controller was duplicated from Element (previously Riot) in the Tchap modules in order to customize it. We want to consider again this screen by restarting with the current Element code.
- [x] replace the current RoomViewController and its dependencies by considering the Element/Riot/Modules/Room folder content. This change must be robust to the following rebase (I mean the new sources should be linked to the actual Element sources)

During this task we will lose some adjustments performed for Tchap. By default consider the Element layout/design, by keeping me informed. I list here some points impacted by this change:
- [x] We will still hide all the encryption icons in all the bubbles - please see [here](https://github.com/tchapgouv/tchap-ios/blob/develop/Tchap/Modules/Room/RoomViewController.m#L1856) this point in TchapV1 where the boolean `showEncryptionBadge` is forced to be false
- [x] We have to add the Tchap bubbles views created for the attachments (to manage the content scanner) [see](https://github.com/tchapgouv/tchap-ios/blob/develop/Tchap/Modules/Room/RoomViewController.m#L1865)
Caution: We don't need to keep the layout created with the encryption icons (`RoomEncryptedAttachmentAntivirusScanStatusBubbleCell`, `RoomEncryptedAttachmentAntivirusScanStatusWithoutSenderInfoBubbleCell`and `RoomEncryptedAttachmentAntivirusScanStatusWithPaginationTitleBubbleCell`). The boolean `showEncryptionBadge` is always false for the moment in Tchap.
- [x] A specific feature has been implemented in Tchap-iOS in order to be able to create a DM only when the user sends his first message. This feature was handled by the param [`discussionTargetUser`](https://github.com/tchapgouv/tchap-ios/blob/develop/Tchap/Modules/Room/RoomViewController.m#L211), which let the application open a RoomViewController without an actual room. This mechanism will not be ported here, all the related code will be ignored. Element will add this feature later. 
- [x] Note: we still don't have `splitViewController` in Tchap, comment the related code in the new RoomViewController code.
- [x] Selected message: during this change we will keep the same options as Element on the selected message
![image](https://user-images.githubusercontent.com/8969772/147887490-89d3142e-e16a-4289-a7c6-8e84051c8be5.png)
This means you don't have to keep the existing compilation flag use to disable Edition and Reaction. We will support now these 2 options by default in Tchap-iOS (Prod/Preprod). You can drop any existing adjustments on this menu in Tchap.
- [x] Room preview: The related code is under the method `- (void)showPreviewHeader:(BOOL)isVisible`.
Tchap-ios introduced a banner `PreviewView` displayed under the room header, in order to not use the existing `PreviewRoomTitleView` which overlaps the room header (navigation bar). Here is a screenshot with both rendering (Tchap on the left/ Element on the right):
![Screenshot 2021-12-31 at 15 32 54](https://user-images.githubusercontent.com/8969772/147828930-8851a992-80b3-4c68-aa21-16378f5e4e73.png)
We will use the Element rendering (based on `PreviewRoomTitleView`) except if this title view is not compatible with the rest of the Tchap code.
This means we will have to support again all the [xxxTitleView classes](https://github.com/vector-im/element-ios/tree/develop/Riot/Modules/Room/Views/Title), except 'ExpandedRoomTitleView'. This last one is not used anymore in Element.
- [x] InputToolbar: The Tchap input toolbar will be totally replaced with the recent [Element one](https://github.com/vector-im/element-ios/tree/develop/Riot/Modules/Room/Views/InputToolbar) which is a very good thing.
When the new input toolbar will be set. We have to hide (comment) in Tchap the 2 following options:
- the stickers (the second icon in the following screenshot:
![image](https://user-images.githubusercontent.com/8969772/147829807-93416395-8c74-4326-8fff-3a41905c0825.png)
- the voice message (see the microphone at the end of the text input:
![image](https://user-images.githubusercontent.com/8969772/147829852-07bf5900-11ed-4664-900c-e3f636ae470f.png)

- [x] RoomBubbleCellData: You can use the Element [code](https://github.com/vector-im/element-ios/blob/develop/Riot/Modules/Room/CellData/RoomBubbleCellData.m), and ignore the current Tchap version.
I would just ask only to add `MXEventTypeRoomRetention` type support in the Element RoomBubbleCellData code

**Comment by giomfo** [comment]
When the change will be effective, 
- [ ] the new created room should be displayed like in Element-iOS with the Tchap theme
![image](https://user-images.githubusercontent.com/8969772/147887663-9bbdbf7f-0b2d-4952-bf21-4a22ade09e90.png)
The displayed options (invite/topic...) must be tested and linked to the right screen
- [ ] the following button "jump to unread" should work like in Element with the Tchap theme
![image](https://user-images.githubusercontent.com/8969772/147887769-d24c1e21-1999-4973-af1c-2c16f01864b9.png)

**Comment by yostyle** [comment]
1. No AV Scan/Result
2. Reactions are not displayed under messages but we can see them in reactions history or in reactions bar.
3. splitViewController is still present in RoomViewController
4. Copy / Create a link doesn't work

**Comment by phlniji** [comment]
1. This point is fixed in the latest commits.
2. Same as 1.
3. SplitViewController is disabled only when needed, to simplify rebases from Element.
4. It fails only on iOS Simulator. It works on real device.

**Comment by giomfo** [comment]
@phlniji well done, I checked all the boxes, I will create 2 issues about issues I observed following this change
