### ISSUE TITLE
Failed messages are stuck in the notification area

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#455]
The notification area is not updated after deleted all failed messages

To reproduce:
- send twice message while the device is off
-  stop/start the application
- we see the following notification at the bottom of the room OK
 <img width="408" alt="image" src="https://user-images.githubusercontent.com/8969772/155532578-be12a0ab-bbbb-4714-8cc2-c1a9eb20ada7.png">
- I click on the track icon
- a dialog is displayed to confirm the message deletion, I confirm
- the 2 failed message are removed from the timeline, but the notif is stuck at the bottom

**Comment by giomfo** [comment]
Selected to investigate it in Element-iOS, and eventually fix it if this is not already done

**Comment by phlniji** [comment]
Not reproduced on latest Element iOS version (1.8.23).

**Comment by phlniji** [comment]
And not reproduced in Tchap 2.0.3 too.

**Comment by giomfo** [comment]
I will test again before closing it

**Comment by giomfo** [comment]
test ok
