### ISSUE TITLE
Rebase onto Element iOS 1.8.3 tag

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#461]
target : https://github.com/vector-im/element-ios/releases/tag/v1.8.3

a first rebase will be done against [1.7.0](https://github.com/vector-im/element-ios/releases/tag/v1.7.0)

**Comment by phlniji** [comment]
PR for the first part of the task (Rebase onto Element iOS 1.7.0 tag) :
https://github.com/tchapgouv/tchap-ios/pull/469

**Comment by giomfo** [comment]
note: I observed a wrong icon color
<img width="97" alt="image" src="https://user-images.githubusercontent.com/8969772/156746768-08755b68-5e72-46c1-b35a-dfe60eaa18ef.png">

**Comment by phlniji** [comment]
To finish this rebase, we need to remove accessToken injection on MXHTTPClient with these tasks :
- ThirdPartyIDResolver: #471
- UserService: #472
- AccountValidityService: #473

**Comment by phlniji** [comment]
> note:
> 
> * [ ]  I observed a wrong icon color
> 
> <img alt="image" width="97" src="https://user-images.githubusercontent.com/8969772/156746768-08755b68-5e72-46c1-b35a-dfe60eaa18ef.png">
> 

The source image has a white arrow inside.
So, tinting this image will not solve this issue, and we need to replace this image.

**Comment by giomfo** [comment]
this last point will be handled by #481
