### ISSUE TITLE
[Room Settings] Let the admin convert a forum in a private room

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#466]
Following #456, in case of a forum, if the end user is the room admin, we have to add the following option: 
<img width="470" alt="image" src="https://user-images.githubusercontent.com/8969772/156238728-93aac4c7-13db-4a23-b995-2cea4763de11.png">

The expected behavior is well described in https://github.com/tchapgouv/tchap-android-v2/issues/209

**Comment by giomfo** [comment]
blocked by https://github.com/tchapgouv/tchap-design/issues/82

**Comment by NicolasBuquet** [comment]
Option discarded : converting a forum to a private encrypted room is too costly back-end side for a forum with a lot of participants.
