### ISSUE TITLE
Restore incoming self verification request

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#488]
Following #484, the incoming self verification is not displayed

To reproduce:
- log in a Tchap on the web client
- send/receive some messages
- log in on Tchap-iOS with this account
- the user is prompted on the web client to verify this new session
- accept on the web client, a loading wheel is displayed on the web client, but nothing is displayed on tchap-ios

**Comment by phlniji** [comment]
Not reproduced
