### ISSUE TITLE
Blank screen after a clear cache

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#505]
Blank screen on clear cache 👍 
<img width="468" alt="image" src="https://user-images.githubusercontent.com/8969772/163390914-d2d6901b-1063-4965-8e24-8ca06c0492a1.png">

The rooms are back after a cold restart of the application

**Comment by phlniji** [comment]
I cannot reproduce this issue with the current version on `develop`, even on iPhone (device) with iOS 14.8, or iPhone Simulator on iOS 15.4.
@giomfo Do you still have the issue ?
