### ISSUE TITLE
[Room settings]  Remove the unexpected chevron displayed on the room access settings

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#524]
<img width="412" alt="image" src="https://user-images.githubusercontent.com/8969772/167470898-f6471edc-6033-45a2-8359-25a06f8c2adb.png">

This chevron is displayed if the end user is the room admin
This chevron is not useful because no more settings are available, so the end user must not be invited to click on it

**Comment by NicolasBuquet** [comment]
The chevron is no more present in Tchap v2.6.2.
