### ISSUE TITLE
Favories rooms have different icon accross the app

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-ios#533]
In the home screen : star icon
When we slide a room : pin icon

**Comment by giomfo** [comment]
@jdauphant which icon should be kept the star icon (from Element) or the pin icon (from Tchapv1)?

**Comment by jdauphant** [comment]
Maybe we can align with Element, @areox-net @Caroline-lawson what do you think ?

**Comment by Caroline-lawson** [comment]
Agreed. Also, starring and pinning are actually different actions. Starring here makes more sense.
