### ISSUE TITLE
[1.99.2] - La majorité des nouveaux messages en échec de déchiffrement depuis la MàJ

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-ios#534]
Avant 14h : Version 1.2.3 installée - RAS

Autour de 14h : 
- export des clés en vue de la MàJ
- remplacement de 1.2.3 par 1.99.2
- import des clés sur 1.99.2

--> Les anciens messages (ceux échangés avant la MàJ) sont correctement déchiffrés.

En revanche, la plupart des messages reçus après 14h (donc après la MàJ) sont en échec de déchiffrement : 

- Ceux que j'envoie moi même depuis le web
- Ceux de Philippe Li.
- Ceux de Nivann
- Ceux de Claire
- Certains messages de Julien, mais pas tous
- Certains messages de Nicolas, mais pas tous

En revanche j'arrive à lire tous les messages d'Estelle en DM comme dans les salons (jusqu'à présent).

L'échec de déchiffrement concerne aussi bien les DM que les salons privés.

- Impossible de demander le partage des clés depuis l'iPhone (le clic sur Re-request encryption keys ne produit aucun effet)
- Le pb n'est pas résolu par un clear cache

**Comment by giomfo** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/8969772/169255557-6f535510-e6b9-4714-816d-68503fb7c9bc.png">
@JDixmier peux tu indiquer le resultat de ce test

**Comment by JDixmier** [comment]
Test fait à 12h20 : pour l'instant, tout semble fonctionner normalement
