### ISSUE TITLE
[DM] Unable to start a new DM with a contact who left the previous DM

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#535]
When I select a contact who left our last DM, Tchap automatically displays this existing DM left by the selected contact

It was on purpose in Tchapv1 to invite again the user on a new message. Now we are back on Element this mechanism is not available (until https://github.com/vector-im/element-meta/issues/120)

I request here to stop display the left DM and create a new DM in this use case for the moment (like in Element)

**Comment by jdauphant** [comment]
A loading feedback whould be nice

**Comment by jdauphant** [comment]
The main problem is present in Element iOS. It should be fixed there.

**Comment by giomfo** [comment]
@jdauphant I will close this issue related to the left DM
I created https://github.com/tchapgouv/tchap-ios/issues/554 to track your second pb.
Do you agree to block this second issue until we deliver Create DM room only on first message #483?
