### ISSUE TITLE
History of the favorite rooms is missing

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#546]
I marked as favorite one of my room maned "ultime room"
The last message is missing in the room cell in the favorite rooms list  (tab Favorites)
<img width="394" alt="image" src="https://user-images.githubusercontent.com/8969772/170197913-9cab4d55-e272-44d8-888c-5bd986087110.png">
and the room history is empty when I open it from this tab, whereas I see the full history if I open it from the rooms tab

<img width="375" alt="image" src="https://user-images.githubusercontent.com/8969772/170198140-2cc74774-ca22-4b41-9f71-225e225ccf47.png">

Note: the pb is persistent even after a clear cache

**Comment by phlniji** [comment]
Not reproduced
