### ISSUE TITLE
Error total count of "persons"

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-ios#551]
![ima_c459b91](https://user-images.githubusercontent.com/1238254/171033750-e892994e-1c4d-48ba-a6a7-aed9b44dbd5c.png)

`Personnes *4*` but only 2 are showed

**Comment by jdauphant** [comment]
Looks like the probleme is solved in 2.0.0

**Comment by giomfo** [comment]
I don't reproduce this issue
@jdauphant can you test again on v2.0.2?

**Comment by giomfo** [comment]
we consider it fixed
