### ISSUE TITLE
[DM] Improve the new created DM navigation flow

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#554]
User feedback: "In fact, It's strange. The invitation is created but it's not visible immediatly, I don't have the feedback that the DM has been created" (see [details](https://github.com/tchapgouv/tchap-ios/issues/535#issuecomment-1141198477)

We should improve the navigation handling in the [createNewDiscussionCoordinator](https://github.com/tchapgouv/tchap-ios/blob/develop/Riot/Modules/TabBar/TabBarCoordinator.swift#L1036) function of the TabBarCoordinator. We should wait for the DM to be ready before dismiss the current module. A loading wheel may be displayed until the new DM is available...

I would wait for https://github.com/tchapgouv/tchap-ios/issues/483 before considering this issue. "Create DM room only on first message" should fix the current pb.

**Comment by jdauphant** [comment]
@giomfo I have tested on Element iOS :
- create a DM from alice to bob 
- accept the invitation from bob
- leave the DM from bob
- create a DM from alice to bob
- we go the old DM that bob have left :( 

Maybe this should be fixed in Element ?

**Comment by giomfo** [comment]
@jdauphant About Element, I do my best to promote the following change : https://github.com/vector-im/element-meta/issues/120 (which was the behavior implemented for tchap-v1)
For the moment, Element-iOS, opened the left DM, and this is not considered as a pb because the end user can invite again the left member (but I disagree with that)

Tchap blocks the invite in DM (this is not allowed client and server side), so open the left DM was a pb. We fixed it via #353

Hope I'm clear, but to sum up, we have to discuss how Element should change to satisfy Tchap (and sponsor this request of change)

**Comment by jdauphant** [comment]
I have seen someone with cache problem on iOS, in that case, a second DM was created.
