### ISSUE TITLE
[Salons] Update the message preview stripe with matest design 

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-ios#561]
We should update the design of the message preview stripes in order to be consistent with Tchap Android:

- only Forums have an avatar icon
- this Forum icon has changed. It is now a slashed lock
- we don't display the "privé" label anymore

![IMG_2827](https://user-images.githubusercontent.com/1255251/172658193-5f4cee79-bb89-42c9-b6a8-8deeea1ba7bd.PNG)

**Comment by NicolasBuquet** [comment]
Too old. The design changed.
