### ISSUE TITLE
[Salons] Replace section name "Conversations" with "Salons"

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-ios#563]
Everything is in the title

**Comment by giomfo** [comment]
Done in Tchap-iOS v2.0.0.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/8969772/172663181-0177770d-dfe0-4efc-b588-4769a1d4871d.png">

**Comment by giomfo** [comment]
I just realized you're talking about section title
<img width="396" alt="image" src="https://user-images.githubusercontent.com/8969772/172663372-69678a16-4ff2-4bd3-bd81-0b223b3f8939.png">
I reopen the issue

**Comment by giomfo** [comment]
We should consider all occurrences of "conversations" in the application

**Comment by giomfo** [comment]
@areox-net @jdauphant do you agree to use this issue to replace all "Conversations" occurrences with "Salons" (this means use the existing Element-iOS French translation for rooms)

**Comment by areox-net** [comment]
@giomfo Yes, this should be the best way to do it.
