### ISSUE TITLE
[Rooms list] Fix multiple empty cells on filtering rooms with no result

### ISSUE THREAD

**Issue by phlniji** [tchapgouv/tchap-ios#571]
As described [here](https://github.com/tchapgouv/tchap-ios/pull/560#pullrequestreview-1004318143), sometimes when filtering rooms in rooms list, there are multiple cells with "Aucun résultat" instead of only one (or none in Element).

**Comment by NicolasBuquet** [comment]
Fixed by rebase on Element 1.8.16
