### ISSUE TITLE
[Settings] Move back to Element settings screen

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#576]
Currently we are using a specific Tchap settings screen based on Riot-iOs settings

We want here to update Tchap-iOS settings screen by using the most recent Element-iOS screen.
I will share here several screenshots (left: Element, right: Tchap), by marking :
- in red what we want to hide from Element-iOS
- in green what we want to keep from Tchap-iOS

<img width="822" alt="tchap-settings" src="https://user-images.githubusercontent.com/8969772/174271654-d93fb088-aa5c-439f-b0d7-4c91876ae99f.png">
I will detail here the change password point:
We improve in Tchap the change password flow : alert the end user about the potential loss of history + support Apple strong password service. We will have to keep this new flow. We will have to apply this change in Element-iOS in parallel (an issue should be created for that in Element-iOS).
<img width="631" alt="image" src="https://user-images.githubusercontent.com/8969772/174273439-57f73de8-b11d-4d9e-b10f-3f283847a2f0.png">

<img width="819" alt="tchap-settings2" src="https://user-images.githubusercontent.com/8969772/174277659-8266d2f9-ae9e-4016-b9d7-ded1c1002715.png">
<img width="815" alt="tchap-settings3" src="https://user-images.githubusercontent.com/8969772/174278282-648b87eb-0397-4f07-a68f-c55194276100.png">
<img width="813" alt="tchap-settings4" src="https://user-images.githubusercontent.com/8969772/174279890-6b18b992-c708-49f9-b235-a735717269d9.png">
<img width="811" alt="tchap-settings5" src="https://user-images.githubusercontent.com/8969772/174280524-c8880605-651b-45bc-a96a-3d0c1810d125.png">

**Comment by giomfo** [comment]
> As requested this afternoon by Angelo, we also should move down the "Se déconnecter" button under the "Désactiver mon compte" one.

@areox-net, can you please create an issue in Element-iOS to present your request, I will then submit it to the designers who may agree to change this in Element-iOS. My plan is to limit customisation in these settings. We already have to manage the existing differences
@phlniji cc

**Comment by areox-net** [comment]
@giomfo Here is the issue in Element-iOS https://github.com/vector-im/element-ios/issues/6362
