### ISSUE TITLE
Add clear cache option from the Apple settings

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#579]
To deal with the migration from v1.2.3 to v2.0.x, we consider useful to trigger a clear cache when the application launch again after a crash.

This systematic clear cache mecanism should be optional by a configuration flag (because clear cache may have cost (data consumption) for the end users)

**Comment by phlniji** [comment]
We discussed about another mechanism :
We should add a Settings bundle to the app, with a switch to let the user do a manual clear cache on application startup.

**Comment by giomfo** [comment]
@phlniji I don't see the option in the system settings, where it is supposed to appear?
