### ISSUE TITLE
Les gif ne sont pas lus de manière automatique

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-ios#592]
Les gif ne sont pas lus de manière automatique, ce qui laisse croire aux utilisateurs qu'ils ne fonctionnent pas

![IMG_6069](https://user-images.githubusercontent.com/45665538/175916215-9e579ffe-0772-4b8b-bdbf-ce23474df510.PNG)

**Comment by giomfo** [comment]
This is the same behaviour in Element-iOS
We should check first with the Element-iOS team how to improve this point
