### ISSUE TITLE
Demandes de partage de clés apparaissent en retard

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-ios#600]
Le pb est constaté quand je demande le partage de mes clés depuis le web (v4 et v2.5.3)
La demande n'apparaît pas sur mon app iOS sur le moment
En revanche, des demandes apparaissent aléatoirement sur iOS à d'autres moments

**Comment by giomfo** [comment]
@JDixmier je me demande si je n'ai pas observé le meme pb sur l'un de mes simulateurs

il est possible que ce soit une séquelle de nos mises a jour intermediaires. Les logouts successifs de la version v1.99.x

- combien de session iOS sont visibles dans tes appareils depuis le client Web ?

**Comment by jdauphant** [comment]
@phlniji @yostyle do we have and update on this ticket ?
We got an user that have created account on Tchap iOS and later, he connects to tchap.gouv.fr, he haven't received a validation request in the following 10 minutes.

**Comment by JDixmier** [comment]
@giomfo 5 sessions sont visibles depuis le client web

**Comment by giomfo** [comment]
> @giomfo 5 sessions sont visibles depuis le client web

@JDixmier il faudrait supprimer les sessions iOS non valides

**Comment by giomfo** [comment]
@JDixmier do you still observe the issue? can we close it?

**Comment by giomfo** [comment]
thank for the feedback
Did you restart the Tchap-ios application on your device?

**Comment by JDixmier** [comment]
No, should I do it ?

**Comment by JDixmier** [comment]
Indeed the pop-up thats asks to share the keys appears on the iPhone after restarting the app

**Comment by giomfo** [comment]
considered done for the moment
