### ISSUE TITLE
[Cross signing] Disable the cross-signing logic until we are ready to support it

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#605]
Following #577, we should prepare a new version of Tchap-iOS in which the cross-siging logic is totally disabled. For example we should not used `canCrossSign` to define shield color.

We should extend the use of the existing Flag which currently hide the UI related cross-signing

Note: We plan to enable later the cross-signing support in Tchap thanks to this flag

**Comment by phlniji** [comment]
After testing the app, we can observe than the cross signing state never changed to another than notBoostrapped. 
So, the use of methods like `canCrossSign` won't affect the crossSigning status.
