### ISSUE TITLE
[Tchap v2] Prompt the last room admin before letting him leave the room

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#610]
@jdauphant by moving back on Element source code, we lost this feature delivered [here](https://github.com/tchapgouv/tchap-ios/issues/218) on Tchap-iOS v1.

This feature is missing in Tchap-iOS v2.0.2 
- is it a blocker?
- how should we restore it? I would vote to request this change in Element on all platforms (by creating an issue in https://github.com/vector-im/element-meta/issues)

We have to be aware that this request is less required for Element because people are able to invite new people in a room left by all the admins. But in any case, Element or Tchap a room should not be without admin

I ping here @areox-net here because he already suggested a UI to force the last admin to select one or more new admin in the existing members before leaving. It may be a good point to present the suggestion in this Element issue

**Comment by jdauphant** [comment]
It's only implemented on iOS v1 ?

**Comment by areox-net** [comment]
I will prepare some mockup to suggest the enhancement to Element. It's a simple modal message, so it should be easy to add.

**Comment by NicolasBuquet** [comment]
Fixed by https://github.com/tchapgouv/synapse-manage-last-admin
