### ISSUE TITLE
[Tchap v2 - Add room member] - Wrong langage in the prompt displayed on contact selection

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#613]
The current dialog is in French and in English:
<img width="322" alt="Screenshot 2022-07-08 at 17 19 59" src="https://user-images.githubusercontent.com/8969772/178022049-0f9482a6-1679-4cce-a14d-f41c88d3e52c.png">

**Comment by phlniji** [comment]
The string was not translated in Element at the previous rebase.
So, we should wait until the next rebase to have it in French.
