### ISSUE TITLE
[Tchap v2] Application is frozen after renewing the account

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#615]
To reproduce:
- open Tchap-iOS whereas the account is expired
- a dialog is displayed because the account is expired OK
- click on the link received by email
- click "I renew my account" in the dialog displayed in Tchap-iOS
- the app is refreshed OK
- **BUT**: click on a room in the rooms list do nothing (on all the tabs: fav/direct/rooms) **NOK**

Note: stop and restart the application fix the pb

**Comment by jdauphant** [comment]
Is it simple to solve?

**Comment by phlniji** [comment]
This issue is not reproduced each time. So it's difficult to test it and to test the potential fix.

**Comment by giomfo** [comment]
I will test it before

**Comment by giomfo** [comment]
Test ok
