### ISSUE TITLE
Replace https://tchap.beta.gouv.fr/faq by https://www.tchap.gouv.fr/faq

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-ios#617]
https://www.tchap.gouv.fr/faq is a more permanent url

https://tchap.beta.gouv.fr/faq is use temporary, waiting for a liberation of tchap.gouv.fr for a landing page

**Comment by phlniji** [comment]
@jdauphant Is this change mandatory for you for the v2 app release ? 
It's a small change, but we should build a 2.0.4 version with this fix.
