### ISSUE TITLE
Request to Apple the Additional capability Notification (NSE) Filtering

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#635]

**Comment by phlniji** [comment]
Here are the requested informations by Apple :
- AppName : Tchap (and Btchap / DevTchap too ?)
- AppStore URL : https://apps.apple.com/us/app/tchap/id1446253779
- Apple ID of App : 1446253779
- AppType : Messaging
- Does your App provide end-to-end encryption ? Yes
- Explain why existing APIs are not adequate for your app
- Explain why your app doesn’t show a visible notification each time a push notification is received
- When your extension runs, what system and network resources does it need ?
- How often does your extension run ? What can trigger it to run ?

**Comment by NicolasBuquet** [comment]
Done in #941
