### ISSUE TITLE
[Project cleaning] Remove unused Tchap source files

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#636]
We moved back several modules on the Element source code during the previous months
I request here to remove definitely unused Tchap source code (from Tchap sub folder)
Please create an issue for each module (feature) which was not moved back to Element yet in order to take a decision on them

**Comment by phlniji** [comment]
After these changes, there is still Tchap specific code for those parts :
- Authentication / Account creation
- Change Password / Forgot Password
- Account Validity
- Password Policy
- App version checker
- Favorites
- Global Search
- Avatar
- Home
- Forward
- Public Rooms
- Room Creation
- Room Preview
- 3PID
- Media Service
- Invite
- Identity Service
- Home Server
- Display Name

**Comment by giomfo** [comment]
We will track the pending list with #663
