### ISSUE TITLE
Replace Contacts picker by the Element iOS one

### ISSUE THREAD

**Issue by phlniji** [tchapgouv/tchap-ios#638]
Currently, Element iOS and Tchap iOS have not the same contacts picker.
We use a specific one for Tchap, but we should use the Element one.

And we also have a duplicate dataSource for this. So we need to remove the Tchap specific dataSource currently called `ContactsDataSourceTchap`

**Comment by giomfo** [comment]
This picker is used in multiple cases:
- start a new DM
- invite a new room member

- [ ] The Element picker displays a tile to prompt the user to access the contact book, we will hide this tile in Tchap in all cases
- [ ] in case of a new DM, we will hide in Tchap the "invite friends.." button 
<img width="366" alt="image" src="https://user-images.githubusercontent.com/8969772/181817757-d642dbd9-81ca-4d3f-800d-67bd6ac2be4e.png">
- [ ] in case of the invite of new room member, we will keep display the option "share invite link". The handling of this option should be improved in Element-iOS [see](https://github.com/vector-im/element-ios/issues/6496)
<img width="372" alt="image" src="https://user-images.githubusercontent.com/8969772/181819660-c2a52f21-4975-474f-9dd2-166d816d0485.png">
