### ISSUE TITLE
Realign Tchap to Universal Links changes from Element iOS

### ISSUE THREAD

**Issue by phlniji** [tchapgouv/tchap-ios#639]
As seen with the last rebase (1.8.20), there is some changes to the Universal Links management in Element iOS.

We also saw that Element iOS need a fix to the method definition `- (BOOL)handleUniversalLinkFragment:(NSString*)fragment fromURL:(NSURL*)universalLinkURL` in header file. This method has been renamed `- (BOOL)handleUniversalLinkFragment:(NSString*)fragment fromLink:(UniversalLink*)universalLink` in the implementation file.
And I think it's the source of the bug mentioned here : https://github.com/vector-im/element-ios/issues/6492

**Comment by pixlwave** [comment]
@phlniji There's a PR to fix those now open on Element iOS: https://github.com/vector-im/element-ios/pull/6522

**Comment by giomfo** [comment]
@phlniji I will let you close this issue when everything will be ok (depend on the next rebase)
