### ISSUE TITLE
[Dark mode] Wrong background color is applied to describe an infected media

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#642]
see the following screenshot
<img width="351" alt="image" src="https://user-images.githubusercontent.com/8969772/181762232-614f28b1-3e57-497b-9e41-67e2b582961c.png">

**Comment by phlniji** [comment]
In my opinion, the issue is not the text color but the light gray background color. It should be darker when dark mode is enabled.

**Comment by phlniji** [comment]
I applied the same background color as the others cells in the room timeline to fix this.
