### ISSUE TITLE
[Presence] the presence info should not be displayed when the feature is not supported server side

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#661]
All the members of a room are displayed offline except the current user (displayed in the first position)
<img width="136" alt="image" src="https://user-images.githubusercontent.com/8969772/185960060-d4a347d9-c3c7-4056-a828-47f18f1d7e5c.png">

This presence information is not relevant, and should be hidden
This request is linked to https://github.com/vector-im/element-ios/issues/6597

**Comment by giomfo** [comment]
Fix merged in Element-iOS: https://github.com/vector-im/element-ios/pull/7342

**Comment by NicolasBuquet** [comment]
Merged in Rebase 1.10.2
