### ISSUE TITLE
Set Tchap as user agent instead RiotNSE

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-ios#664]
I see lot of active user with RiotNSE/2.0.5 as user agent, but their is no Element or Riot version 2.0.5, but there is Tchap 2.0.5 :
![image](https://user-images.githubusercontent.com/1238254/187495127-a6addd02-fc8c-4316-ad9b-ab8cb3d64098.png)

**Comment by jdauphant** [comment]
The product name of Tchap is "RiotNSE" (PRODUCT_NAME = RiotNSE" ) so in the UserAgent, we see "RiotNSE"

**Comment by giomfo** [comment]
In case of renaming, it would be TchapNSE, this is not possible to name Tchap the NSE extension
If we agree on this naming, we should check the impact on the rebase process

**Comment by giomfo** [comment]
> What about changing the value of the `CFBundleName` manually in the `Info.plist` file of RiotNSE target ?

yes, or you can change the PRODUCT_NAME = RiotNSE in the Common file

The main point is to reduce the impact of this change on the rebase process.

**Comment by NicolasBuquet** [comment]
The first part of the user-agent is determined as follow : 

```
#if TARGET_OS_IOS
    userAgent = [NSString stringWithFormat:@"%@/%@ (%@; iOS %@; Scale/%0.2f)", [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleExecutableKey] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleIdentifierKey], [[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleVersionKey], [[UIDevice currentDevice] model], [[UIDevice currentDevice] systemVersion], [[UIScreen mainScreen] scale]];
#elif TARGET_OS_TV
    userAgent = [NSString stringWithFormat:@"%@/%@ (%@; tvOS %@; Scale/%0.2f)", [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleExecutableKey] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleIdentifierKey], [[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleVersionKey], [[UIDevice currentDevice] model], [[UIDevice currentDevice] systemVersion], [[UIScreen mainScreen] scale]];
#elif TARGET_OS_WATCH
    userAgent = [NSString stringWithFormat:@"%@/%@ (%@; watchOS %@; Scale/%0.2f)", [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleExecutableKey] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleIdentifierKey], [[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleVersionKey], [[WKInterfaceDevice currentDevice] model], [[WKInterfaceDevice currentDevice] systemVersion], [[WKInterfaceDevice currentDevice] screenScale]];
#elif defined(__MAC_OS_X_VERSION_MIN_REQUIRED)
    userAgent = [NSString stringWithFormat:@"%@/%@ (Mac OS X %@)", [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleExecutableKey] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleIdentifierKey], [[NSBundle mainBundle] infoDictionary][@"CFBundleShortVersionString"] ?: [[NSBundle mainBundle] infoDictionary][(__bridge NSString *)kCFBundleVersionKey], [[NSProcessInfo processInfo] operatingSystemVersionString]];
#endif
```

The modification of the `Executable file` property of the Info.plist of RiotNSE target survive `xcodegen generate` command.

I will try to change this Info.plist property to 'TchapNSE' and check with  the OPS if it reaches the backend and doesn't mess with the app.

**Comment by NicolasBuquet** [comment]
Changing the `Executable file` only is refused by AppStore on upload, because the executable filename must match the extension package name.

So, I changed `PRODUCT_NAME` instead to TchapNSE.

It seems to work : notifications are still rooted to the extension.
