### ISSUE TITLE
Tchap iOS 16 bugfixes

### ISSUE THREAD

**Issue by phlniji** [tchapgouv/tchap-ios#671]
Element already fixed some bugs specific to iOS 16, but the fixes are not available on Tchap at this time.
Tchap will get them with the task #669 

Here is a list of the current known and fixed bugs by Element:
- Big gap between messages in room and missing words at the end of messages : https://github.com/vector-im/element-ios/issues/6441
- Name pills are replaced by a generic document icon : https://github.com/vector-im/element-ios/issues/6442

Some other bugs are specific to Tchap/Element app when build with Xcode 14. But at this time, no Tchap version delivered to public (via AppStore or TestFlight) has been built with Xcode 14.

**Comment by giomfo** [comment]
Done, will be deployed with v >= 2.2.0
