### ISSUE TITLE
Users names are duplicated in DM list 

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-ios#672]
"Olivier et Olivier"
"David et David"
etc

Not all DM have the problem : Arnaud and Didier are not duplicated

![IMG_8407](https://user-images.githubusercontent.com/45665538/196390523-8b9f2be6-996f-4957-ab98-e490d35c372e.jpg)

**Comment by giomfo** [comment]
not reproduced in Tchap-iOS v2.2.1
