### ISSUE TITLE
Systematic crash since the user updated to iOS 16

### ISSUE THREAD

**Issue by JDixmier** [tchapgouv/tchap-ios#673]
> Depuis que j’ai mis à jour mon iPhone en passant d’iOS 15.6 à iOS 16 je ne peux plus utiliser l’application tchap qui se ferme immédiatement.

> J’utilise un iPhone 13pro.
> Je viens de redémarrer mon appareil mais toujours le même problème.
> Espace de stockage de 57g libre

> Le clear cache au démarrage ne résout pas le problème
> Le switch pour le vidage de cache revient à chaque fois en position off

https://app.crisp.chat/website/6dacc68e-de3a-4511-8177-1339616098de/inbox/session_4a9e1e6f-f494-4c4d-8da6-3f290cb4ce84/

**Comment by phlniji** [comment]
From the crash logs received from the AppStore, this issue will be fixed by the next release of Tchap iOS.
We are waiting for the current rebase (#674) to be merge for this.

**Comment by giomfo** [comment]
fixed in v >= 2.2.0
