### ISSUE TITLE
Impossible to use the picture selector, I can't select picture/video (iOS bug)

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-ios#691]
User verbatim for 2.2.1 : 

"Au moment de vouloir insérer une image de la médiathèque, je choisis « sélectionner plus de photos » et je vois brièvement une gallérie et rapidement (moins d’une sec) plus rien, je ne peux pas sélectionner d’images/photos.
Valable dans les messages comme dans le chois de photo de profil."

"Alors je viens de progresser en désactivant « Face ID », j’y arrive presque maintenant mais avec tjs des bizarreries.
Dernier point, si j’autorise toute ma médiathèque dans les réglages généraux>Tchap, cela fonctionne normalement.
Mais j’aurais préféré restreindre au choix manuel…"

"Moi j’ai ça si j’ai FaceTime actif et « photos sélectionnées » dans les réglages iPhone>Tchap>photos>autoriser l’accès aux photos"
![image](https://user-images.githubusercontent.com/1238254/204092155-583c6cec-e725-4c6e-9d10-f7635f149977.png)

Reported by 2 users

**Comment by phlniji** [comment]
As I already answered to the user, it's an iOS bug.
I have it on all my personal devices and other apps from at least the 3 latest major iOS versions.

When you have none of the previous selected pictures on your device again, sometimes iOS won't ask the user to add other pictures in the photo picker like it should.

There are 2 workarounds for this :
- Go to the `Settings` app on the device, reset the parameter to `Toutes les photos`, go back in Tchap and try to send a photo in a message (without the needs to really send it). And after that, come back to the previous settings, and it will force the photo picker UI to ask for selecting photos again.
- The simpler solution, is to go to the `Settings` app too, and there is a button called `Modifier les photos sélectionnées` at the end of the app settings. Then, you can choose again which photos your want to share with Tchap (and update the selection at any time).

And there is no link with features like FaceTime or FaceID.
