### ISSUE TITLE
"Person"/direct tab show some rooms

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-ios#692]
![image](https://user-images.githubusercontent.com/1238254/204287952-ecdd8e34-9bf9-4297-854c-9538ac86a211.png)
Room and forum are visible even if I filter them out

**Comment by giomfo** [comment]
@jdauphant are you sure these unexpected rooms were not marked as direct during previous tests ?

**Comment by jdauphant** [comment]
I don't know.
But I have reopen the app later, and it was correct : 
![image](https://user-images.githubusercontent.com/1238254/204390254-77c244ab-f1e4-49b6-9cd5-24460bf6fa35.png)

**Comment by giomfo** [comment]
cannot be reproduced
