### ISSUE TITLE
Reset password button is white

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-ios#693]
### Steps to reproduce

(see screenshot) 
![IMG_576B72C33035-1](https://user-images.githubusercontent.com/4077729/204544250-065c0643-3f1a-440f-81ac-573b836b9c0d.jpeg)
![IMG_8F2A0A55B344-1](https://user-images.githubusercontent.com/4077729/204544253-06614f6d-4dbd-4619-814f-2cc43bf2a87a.jpeg)

#### What did you expect?
I dont know what is this button

### Will you send logs?

No

**Comment by phlniji** [comment]
Thanks for this issue.
The accent color in Dark mode was not the right one.
