### ISSUE TITLE
Enable Key verification by QRCode

### ISSUE THREAD

**Issue by phlniji** [tchapgouv/tchap-ios#698]
Enable Key verification by QRCode like in Element.

**Comment by giomfo** [comment]
The QRCode is supported only in the Element self verification process.

This process is disabled for the moment in Tchap-iOS:  https://github.com/tchapgouv/tchap-ios/blob/develop/Riot/Modules/KeyVerification/Common/KeyVerificationCoordinator.swift#L132

I think we commented the self verification process to keep using the customised verification (the legacy one)

We did some tests by enabling the self verification, this process prompts the QR code scanning as a first option.
The pb is the QR code is generated only if the cross-signing is enabled.
We observed in some cases this screen without Code, the user has to click on "Impossible de scanner" to start the emoji verification
<img width="365" alt="image" src="https://user-images.githubusercontent.com/8969772/212365134-ced079d6-50df-4fa5-bd10-d50211f12ce7.png">

**Comment by giomfo** [comment]
A case where the code is visible only on one device has been reproduced with Element-iOS
1- Consider an iOS session where the cross-signing is enabled
2- Trigger from this session the verification of a new session
3- Accept the incoming verification request

a QR code is displayed on the new session  screen, but no QR code is displayed on the first session
Note: the new session was on a simulated device (unable to scan), the first one was an actual device
