### ISSUE TITLE
[Mainlining] Remove deprecated endpoint `/_matrix/client/unstable/users/info`

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#717]
During the mainlining of synapse, the specific endpoint `/_matrix/client/unstable/users/info` has been replaced by `/_matrix/client/v1/account_status`
    - The new request format is described in [[MSC3720](https://github.com/matrix-org/matrix-spec-proposals/pull/3720)](https://github.com/matrix-org/matrix-spec-proposals/pull/3720)
    - In addition to the MSC, the endpoint also returns an org.matrix.expired field for each user (if the user exists) that indicates whether the user is expired
    - For the moment this endpoint is not implemented in Element clients. We should plan its implementation at the sdk level

The endpoint `/_matrix/client/unstable/users/info` is still available in the current version of synapse deployed in Prod, but it will be unsupported in the next deployed version.

I request here the following changes:
1 - look for each occurrences of the use of this endpoint in Tchap-iOS
2 - ask the Ops team to update servers on DEV platform in order to observe if an error is prompted in DevTchap - This will let us know if the application has to be updated before the server update
3 - remove this endpoint implementation in the Tchap specific code 
The implementation of the new endpoint will be handled in another issue

**Comment by phlniji** [comment]
The current occurrences of `/_matrix/client/unstable/users/info` calls are not linked anymore with something in current Tchap code (v2.2.3).
We probably lost them with the use of more and more Element code in Tchap since last months.

So I will prepare a PR to remove all the useless code.

**Comment by odelcroi** [comment]
@giomfo is there anything we need to do in the web client?
