### ISSUE TITLE
[Mainlining] Check lookup endpoint version

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#719]
Since the mainlining, the following endpoint `/_matrix/client/unstable/account/3pid/lookup` (and equivalent `bulk_lookup`) has been removed. The client is supposed to use the v2 identity API (see [[the Matrix specification](https://spec.matrix.org/latest/identity-service-api/)](https://spec.matrix.org/latest/identity-service-api/) for more details).

This change has been already done by aligning Tchap on a recent version of Element.

I create this issue to check that there is no occurrence of this deprecated endpoint. Only the v2 identity API should be used

**Comment by phlniji** [comment]
The current Tchap version (v2.2.3) is not using anymore the old identity API, only the v2 API.
