### ISSUE TITLE
Enable the secure storage for testing

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#720]
Enable the secure storage (cross-signing and secure backup) by prevent the user from typing the security phrase. This option will not be allowed in Tchap.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/8969772/214418090-2f2233ea-df5d-48d4-b941-a9b393d99bf1.png">

Only the security key option is kept

Prepare this version on DevTchap and Btchap

**Comment by giomfo** [comment]
@NicolasBuquet FYI the expected design is described [here](https://github.com/tchapgouv/tchap-design/issues/106#issuecomment-1403434273)

**Comment by NicolasBuquet** [comment]
Work is done on both first configuration of secure backup and reset of secure backup.
It is implemented for all Tchap versions (not only Btchap and DevTchap).

I think all references and files relative to `SecretsRecoveryWithPassphraseCoordinator` should also be deleted. Need confirmation on this.

![IMG_6917](https://user-images.githubusercontent.com/18608158/214913171-762f3785-d291-47de-b257-322096e7a3a1.PNG)
![IMG_6918](https://user-images.githubusercontent.com/18608158/214913199-7f60e638-999b-4284-9784-8cbca9870546.PNG)
