### ISSUE TITLE
Changement wording dans réinitialisation mdp 

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-ios#722]
#### What would you like to do?
Changer la phrase "Relevez vos e-mails" qui s'affiche quand on vérifie son mail après avoir cliqué sur "J'ai oublié mon mot de passe" par "Vérifiez votre boite mail" ou "Vérifiez vos e-mails"

#### Why would you like to do it?
Plus moderne

**Comment by areox-net** [comment]
Je confirme du point de vue design que "Vérifiez votre boite mail" me semble plus précis.

**Comment by giomfo** [comment]
@phlniji can you please check with Element design team in order to apply this change in Element-iOS by replacing "Relevez vos e-mails" with "Vérifiez vos e-mails"

**Comment by gaelledel** [comment]
I confirm that we should change to "Vérifiez votre boite mail" Thanks for flagging up!

**Comment by NicolasBuquet** [comment]
This change in wording will be done in Element-iOS and integrated in a coming rebase. So I close this issue.
