### ISSUE TITLE
Activate automatically cross-signing on iOS client

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#735]
Actually, the back-end supports cross-signing and secure storage.

The web client and Android client seems to automatically activate cross-signing on launch.

It's not the case on iOS : the user must activate cross-signing in the Parameters/Security settings.

It would be nicer to activate the cross-signing automatically for the user on iOS too. No user interaction is required for this, as on web and Android clients.

**Comment by NicolasBuquet** [comment]
Should be done on Element side ?

**Comment by giomfo** [comment]
I filed an issue in Element-iOS : https://github.com/vector-im/element-ios/issues/7373

**Comment by NicolasBuquet** [comment]
Done by #942 and #943
