### ISSUE TITLE
The app prompts the user to scan a QR code whereas there is no QR code

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#753]
https://github.com/vector-im/element-ios/issues/3115#issuecomment-1426074547

**Comment by giomfo** [comment]
This has been fixed  by https://github.com/vector-im/element-ios/pull/7381 in Element-iOS (this would be available in the next release > v1.10.3)

**Comment by NicolasBuquet** [comment]
Fixed by #785
