### ISSUE TITLE
Direct Message: Manage encrypted DM in case of invite by email

### ISSUE THREAD

**Issue by giomfo** [tchapgouv/tchap-ios#766]
Currently Tchap-iOS hides the DM created by inviting an email until a matrix account is created and bound to the invited email.

This is a specific code in Tchap. We did that to prevent the user from sending messages in an encrypted DM until the invited user is able to receive encryption keys.

To be able to remove this specific code, we discuss with Element team [here](https://github.com/vector-im/element-meta/discussions/571) to support correctly encrypted DM in case of invite by email. 
 We decided to hide the text composer in these DM until it is possible to send keys to the invited users

This changes will be achieved in Element-iOS by https://github.com/vector-im/element-ios/issues/6612
When this code will be retrieved in Tchap (via a rebase), the specific code used to hide encrypted DM should be removed from Tchap

**Comment by giomfo** [comment]
Related PRs in Element:
- https://github.com/matrix-org/matrix-ios-sdk/pull/1727
- https://github.com/vector-im/element-ios/pull/7396

**Comment by NicolasBuquet** [comment]
Fixed by #785
