### ISSUE TITLE
Améliorer la visibilité de la FAQ

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#808]
La FAQ n'est pas présente dans l'application iOS au contraire d'Android et du web.

Sur web, elle est présente au premier niveau du menu Utilisateur, via l'option Aide

![image](https://user-images.githubusercontent.com/18608158/232745458-8cbefd86-d27c-48ea-987a-a2d775324c6b.png)

Sur Android, elle est présente dans le menu Utilisateur/Aide et à propos, dans la section "Aide et support".

C'est un lien web qui peut être ouvert dans l'application (cela déclenche une erreur actuellement) ou via le navigateur.

Sur iOS, elle n'est pas du tout présente.

Une première étape essentielle serait de la rendre accessible au premier niveau du menu Utilisateur, comme sur web.

Au plus simple, on peut ouvrir la page web de la FAQ via un navigateur externe. Sinon, on peut ouvrir cette même page web dans une webview présentée dans une sheet sur iOS. Cela éviterait de sortir de l'application.

**Comment by areox-net** [comment]
@NicolasBuquet For more clarity and consistency across platforms, the tab should be simply named "Foire Aux Questions".
(see https://github.com/tchapgouv/tchap-android/issues/912)

**Comment by NicolasBuquet** [comment]
Correction du libellé.

**Comment by NicolasBuquet** [comment]
Correction du libellé en anglais.

**Comment by areox-net** [comment]
@NicolasBuquet Could we easily swap the icons between FAQ and Aide. The "?" icon would be closer to the Android one and also make more sense.
