### ISSUE TITLE
Remplacer le lien de la FAQ dans les paramètres

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-ios#810]
Nouveau lien vers la FAQ : https://aide.tchap.beta.gouv.fr/fr/ qui remplace l'existant dans la section "Aide et à propos" des paramètres.

**Comment by NicolasBuquet** [comment]
Done by #808

**Comment by NicolasBuquet** [comment]
Bad URL.
Should have been:
- dev : https://www.tchap.incubateur.net/faq
- preprod : https://www.beta.tchap.gouv.fr/faq
- prod : https://www.tchap.gouv.fr/faq

Fixed in #811
