### ISSUE TITLE
Rebase iOS Element 1.10.10 minimun (pour permettre le renvoi de clés de chiffrement automatique)

### ISSUE THREAD

**Issue by jdauphant** [tchapgouv/tchap-ios#814]
Element 1.10.10 : https://github.com/vector-im/element-ios/releases/tag/v1.10.10

Changes in 1.10.10 (2023-04-12)

🙌 Improvements

- Crypto: Enable Rust Crypto for all users (https://github.com/vector-im/element-ios/pull/7485)
- Upgrade MatrixSDK version ([v0.26.7](https://github.com/matrix-org/matrix-ios-sdk/releases/tag/v0.26.7)).

**Comment by NicolasBuquet** [comment]
In actual source code, each time the crypto is started, it is given a chance to activate the new cryptoSDK module for current user, based on availability of the module and the roolout level.
```
    // Each time we construct the crypto module (app launch, login etc) we have a chance to try to enable
    // the newer SDK crypto module, if it is available for this particular user.
    [MXSDKOptions.sharedInstance.cryptoSDKFeature enableIfAvailableForUserId:mxSession.myUserId];
```
