### ISSUE TITLE
Améliorer l'UI de la pop-up FAQ

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#818]
La pop-up de FAQ actuelle surgit du bas de l'écran.

Elle peut être refermée classiquement en la glissant du haut vers le bas. Toutefois, pour les utilisateurs non familiers avec ce comprtement système, il peut être préférable d'inclure un bouton de fermeture plus classique en haut à droite.

C'est ce qui a été fait rapidement sur cette itération. Il reste à faire une passe UX/UI pour confirmer ce choix et faire une inteegration UI plus en phase avec la charte Tchap.

![IMG_7157](https://user-images.githubusercontent.com/18608158/234822911-f3934714-0b45-47ff-81de-88bfd355d66c.jpg)

**Comment by NicolasBuquet** [comment]
Ok, mais par contre, le bouton ajouté recouvre un autre bouton de la page web.

Il faudrait prévoir que cet autre bouton disparaisse en usage mobile.

![image](https://user-images.githubusercontent.com/18608158/234825519-a480d1d1-edad-4730-8b46-8da75a529773.png)

**Comment by areox-net** [comment]
Oui, je peux faire ça simplement en CSS.

**Comment by NicolasBuquet** [comment]
Super, merci @areox-net.
