### ISSUE TITLE
[Création de compte] Critères de mot de passe tronqués

### ISSUE THREAD

**Issue by Caroline-lawson** [tchapgouv/tchap-ios#827]
JTBD: Quand je choisis mon mot de passe, 
je veux connaître les critères de mots de passe,
pour créer mon compte rapidement et efficacement.

Problème - Le texte sous le champ de création de mot de passe ne s'affiche pas dans sa totalité. Ce texte liste les critères de création de mot de passe.

Impact - Les users ne voient pas les critères pour créer leur mot de passe. Ils risquent de ne pas pouvoir créer un mot de passe qui remplit les critères nécessaires, et donc de créer leur compte. Ils doivent également passer du temps à en créer un avec des critères au hasard, voire ils pourraient se lasser et abandonner.

Suggestion - Afficher le texte dans sa totalité (il y a la place).

![image](https://user-images.githubusercontent.com/78041311/236245105-8b5f83a0-8270-4543-bb83-2c1b75076e4a.png)

**Comment by NicolasBuquet** [comment]
Lasituation arrive lorsque l'on a activé le mode d'affichage "zoomé" de iOS sur iPhone 12 mini par exemple.
