### ISSUE TITLE
[Message verrouillés] Message en franglais

### ISSUE THREAD

**Issue by Caroline-lawson** [tchapgouv/tchap-ios#828]
**Problème :** La première partie du message est en français, la deuxième en anglais.

![image](https://user-images.githubusercontent.com/78041311/236789653-8f25411a-8c13-4948-914a-05fd782734a8.png)

**Impact :** Certaines personnes pourraient ne pas savoir quoi faire et donc ne pas récupérer leurs messages.

**Suggestion :** Traduire "Re-request encryption keys from your other sessions." par "Demander le déverrouillage des messages.".

**Comment by NicolasBuquet** [comment]
Source du prtoblème :
- une partie du message provient de l'application "Echec de dé"chiffrement"
- une autre partie provient du backend, qui ne gère oas la langue de l'utilisateur.

On est donc dans un affichage d'erreur générique de déchiffrement. Le serveur dit "Impossible" et explique pourquoi en anglais. L'application remonte cette erreur et l'explication à l'utilisateur.

Pas de solution simple et immédiate.

**Comment by NicolasBuquet** [comment]
@pseudonyme21 @mcalinghee Possible de mettre les messages d'erreur backend en FR ?

**Comment by NicolasBuquet** [comment]
Sera traité par #861
