### ISSUE TITLE
[Inviter à rejoindre Tchap] Erreur avec le mainlining 1.83

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#837]
En test sur le mainlining 1.83, on constate le souci suivant.

Il existe 2 manières d'inviter un agent ou un externe sur Tchap.
![tchap-invite - 2023-05-23 at 18 01 15](https://github.com/tchapgouv/tchap-ios/assets/18608158/c2e297f9-5161-464f-b159-1ef9485868f2)

Inviter un agent ou un externe se fait par la création d'un salon Direct Message entre l'inviteur et l'invité.

Le endpoint `/createroom` est appelé sur le back-end.

Avant le mainlining 1.59, seuls 3 paramètres étaient obligatoires. Lors d'une évolution entre la 1.59 et la 1.83, un nouveau paramètre est devenu obligatoire, le `id_access_token`.

Sur Tchap iOS, si l'on invite un agent ou un externe par l'option "Nouveau message direct", tout se passe correctement.

Mais si l'on invite un agent ou un externe par l'option "Inviter à rejoindre Tchap", le back-end renvoie une erreur :

![Simulator Screen Shot - iPhone 14 - 2023-05-23 at 18 09 20](https://github.com/tchapgouv/tchap-ios/assets/18608158/46cb9842-66ab-40ee-aa99-75e24996fa3d)

Les 2 chemins d'invitation ne sont pas les mêmes dans le code iOS :

- l'un appelle `MatrixSDK/Core/MXRestClient/createRoomWithParameters:(MXRoomCreationParameters*)parameters
                                     success:(void (^)(MXCreateRoomResponse *response))success
                                     failure:(void (^)(NSError *error))failure` qui ajoute correctement le 4e paramètre.

- l'autre appelle `Tchap/Managers/Room/RoomService/createRoom(with roomServiceCreationParameters: RoomServiceCreationParameters,
                            completion: @escaping (MXResponse<String>)` qui n'ajoute pas le 4e paramètre.

### Question

Faut-il corriger l'appel spécifique Tchap `RoomService/createRoom` ou faut-il supprimer cette option spécifique à Tchap ?

**Comment by odelcroi** [comment]
> Inviter un externe se fait par la création d'un salon Direct Message entre l'inviteur et l'externe.

Si je comprend bien cette option n'est pas uniquement propre aux externes, je peux inviter par email un agent ?

> Faut-il corriger l'appel spécifique Tchap RoomService/createRoom ou faut-il supprimer cette option spécifique à Tchap ?

Je pense qu'il faut garder le bouton "Inviter à rejoindre Tchap"

Arrive-t-on au meme resultat avec les deux fonctions mentionnées? ie : créer une room privée avec le membre invité?

**Comment by odelcroi** [comment]
est ce que ce ticket est résolu?
