### ISSUE TITLE
[UI] En thème sombre, les titres de section des paramètres sont illisibles

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#856]
![Simulator Screen Shot - iPhone 14 - 2023-06-28 at 16 43 17](https://github.com/tchapgouv/tchap-ios/assets/18608158/7dd95f49-ddd7-4295-976a-ee8d1eb40395)
![Simulator Screen Shot - iPhone 14 - 2023-06-28 at 16 43 40](https://github.com/tchapgouv/tchap-ios/assets/18608158/9464ac5a-1322-473a-bfea-4adf31fde198)

**Comment by areox-net** [comment]
@NicolasBuquet On peut utiliser du pure blanc #FFFFFF
