### ISSUE TITLE
Modifier le texte quand les messages sont verrouillés

### ISSUE THREAD

**Issue by Caroline-lawson** [tchapgouv/tchap-ios#861]
Changer le message "Echec de déchiffrement : Veuillez ouvrir Tchap sur vos autres appareils afin d'autoriser le partage de clés. Re-request your encryption keys [CTA échange de clés] from your other sessions.".

Pour "Ouvrez Tchap sur vos autres appareils [CTA échange de clés] ou insérez votre Code de Récupération pour déverrouiller vos messages [CTA code de récup] .".

Ne pas utiliser de texte en italique parce que c'est peu accessible.

![image](https://github.com/tchapgouv/tchap-ios/assets/78041311/6a9c039f-c998-4db1-b735-a84b3ac73f89)

**Comment by NicolasBuquet** [comment]
Voilà ce que cela donne : 

https://github.com/tchapgouv/tchap-ios/assets/18608158/f6e92c5c-7f19-4b58-916e-50e87e9c1956
