### ISSUE TITLE
Impossible de rejoindre un forum d'un autre homeserver depuis un lien généré sur mobile

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#875]
Sur iOS, un utilisateur  s'est retrouvé dans l'impossibilité de rejoindre un forum. Cette impossibilité a été confirmée par l'équipe de développement avec l'erreur suivante : 
![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/6e537277-8209-41b5-b049-3f01ebee72b4)

Il a été possible de rejoindre le salon depuis le client web.

Suite à cela, l'équipe de développement a pu rejoindre le forum via l'interface de l'application iOS.

L'utilisateur a aussi pu rejoindre le forum grâce à un lien donné par l'équipe : https://tchap.gouv.fr/#/room/!ChBRUBytCvCgWZPUpj:agent.education.tchap.gouv.fr?via=agent.education.tchap.gouv.fr&via=agent.dinum.tchap.gouv.fr

Hypothèse de la source du problème : 

>C'est un bug de la version iOS apparemment, l'application iOS ne doit pas transmettre toutes les informations pour rejoindre le forum (le lien que j'ai indiqué juste au dessus, devrait renforcer cette hypothèse).

>j'ai pu le rejoindre depuis la version web, il faut voir maintenant que le forum est connu depuis l'instance DINUM, tu peux le rejoindre

> si c'est le cas, il se pourrait que l'app iOS ne sait pas comment rejoindre un salon inconnu de son homeserveur de rattachement

>Ok, le problème doit être la version iOS qui ne fournit pas le homeserver éducation au serveur synapse dinum

> Les liens de partages de salon incorporent les homeservers que l'on peut interroger par exemple : (via l'attribut "via")

>En fait, j'ai regardé l'API, il n'y a qu'un seul homeserver fournit dans la spec. iOS doit donner Dinum au lieu d'éducation

**Comment by NicolasBuquet** [comment]
Old issue : #190

**Comment by NicolasBuquet** [comment]
L'activation de l'accès à un salon par lien depuis mobile (iOS ou Android) est moins complète que depuis web.

Exemple de lien d'activation créé depuis mobile : 
> https://tchap.gouv.fr/#/room/#SalonFromTest1VUsOH5zJD8V:agent.dinum.tchap.gouv.fr

Exemple de lien d'activation créé depuis web : 

> https://tchap.gouv.fr/#/room/!myhHblrznHhXmwYohG:agent.dinum.tchap.gouv.fr?via=agent.dinum.tchap.gouv.fr

Dans la création de lien sur mobile, il manque le paramètre `via`.

Ce paramètre est utile quand le lien est partagé à un utilisateur d'une instance qui n'est pas encore relié à l'instance hébergeant le salon. Ce lien sert à savoir sur quelle instance chercher le salon cible.

**Comment by NicolasBuquet** [comment]
Il semble donc que le souci se présente quand le salon fait partie d'un espace.

Sur web, alors qu'un salon fait partie d'un espace, le lien créé à partir du client web contient le paramètre `via` : https://tchap.gouv.fr/#/room/!xsGKyvazNeNLJZAgbH:agent.dinum.tchap.gouv.fr?via=agent.dinum.tchap.gouv.fr

Le salon est accessible aux membres de l'espace.

Le salon n'a pas l'option d'accès par lien dans l'interface web.

Depuis iOS, l'option d'accès par lien est présente et activable.

Après activation sur ce même salon depuis le client iOS, le lien de partage fourni par le web ne contient plus le paramètre `via` : https://tchap.gouv.fr/#/room/#testavecjulie1Ke1fasvWbc5:agent.dinum.tchap.gouv.fr

Le problème pourrait donc se manifester quand un salon est accessible par lien et qu'il a été ajouté à un espace.

**Comment by NicolasBuquet** [comment]
Lié à ce ticket web : https://github.com/tchapgouv/tchap-web-v4/issues/881 ?

**Comment by NicolasBuquet** [comment]
Protocole de recherche de reproduction du souci : 
-déterminer une room ayant un lien sans paramètre `via` et qui pose problème à rejoindre à travers 2 homeServers distincts
- vérifier si l'ajout 'à la main' du paramètre `via` permet de rejoindre cet room à travers 2 homeServers distincts

Si on arrive dans le cas décrit ci-dessus : 
- vérifier si le problème est le même en utilisant les clients Element
- déterminer éventuellement pourquoi le paramètre `via` n'est parfois pas ajouté

**Comment by NicolasBuquet** [comment]
Cela semble finalement être un problème de mauvaise génération de lien de partage.
Confusion entre RoomId et RoomAlias : https://www.notion.so/mercurial-timer-ec4/Les-diff-rents-Matrix-IDs-et-Room-ID-be1d6607038547fe80980505a65bb5b6

**Comment by Delphgateau** [comment]
@NicolasBuquet on peut fermer ?

**Comment by NicolasBuquet** [comment]
@Delphgateau Pas encore. On attend la review et le merge et il se fermera automatiquement (du fait du merge).
