### ISSUE TITLE
ios : Creer une DM avec un Externe

### ISSUE THREAD

**Issue by mcalinghee** [tchapgouv/tchap-ios#876]
### Steps to reproduce

1. Sur iOS, avec un compte interne, creer un message direct avec un externe (existant ou pas)
2. Envoyer un message
3. Revenir sur l'ecran d'Accueil

#### What did you expect?
Sur l'ecran d'Accueil, dans le fil de discussion, on peut voir la discussion avec l'externe

#### What happened instead?
- Sur l'ecran d'Accueil, dans le fil de discussion, on ne voit pas le salon (Message Direct) avec l'externe et donc ne peut revenir dans ce salon pour dialoguer avec l'externe.
- En revanche :
  - on peut s'apercevoir que le salon (Message Direct) avec l'externe est bien présent sur Tchap-web
  - si le salon a été créé dans Tchap-Web avec un compte interne => sur iOS, on voit bien les salons (Message Direct) avec des externes sur l'ecran d'Accueil sous l'onglet Personnes

### Application version

2.4.8

### Will you send logs?

No

**Comment by mcalinghee** [comment]
Pour investiguer, on peut regarder l'appel URL effectue lors de la creation de la room sur Tchap-web ou Android et de comparer avec notre probleme sur iOS

**Comment by NicolasBuquet** [comment]
Peut-être lié au fait que sur iOS, lorsque l'on invite un externe en DM, il n'est pas possible d'écrire un premier message suite à l'invitation (premier message impossible avant acceptation de l'invitation, sinon, souci de chiffrement car ce premier message avant acceptation sera définitivement chiffré pour l'invité).
Ce premier message est possible et même demandé si l'on invite depuis le client web.

**Comment by NicolasBuquet** [comment]
Sur Tchap iOS 2.5.0 en test, l'invitation d'un externe à un salon DM fonctionne mais présente un défaut majeur.

Après envoi de l'invitation, celle-ci ne semble pas reçue dans l'application de l'externe lancée sur simulateur.

Mais en se rendant sur le compte externe dans les paramètres utilisateur puis en revenant sur l'interface générale des salons, celle-ci se rafraîchit et l'invitation est alors visible.

L'accepter permet de rejoindre le salon, qui est alors bien listée sur la version web 4.3.8 dans la liste des Direct Messages.

Par contre, cette room DM n'est pas visible sur iOS (ni en Direct Messages, ni en salon classique).

Lors d'un premier essai, elle était visible sur Android 2.9.2 en Direct Message. Et elle est devenue visible sur iOS.

Lors d'un second essai, elle n'est plus visible sur Android que dans les salons généraux ( et plus dans les DM), et elle n'apparaît plus sur iOS. Elle st toujours listée dans le DM sur web.

**Comment by NicolasBuquet** [comment]
La cause du problème est trouvée : il y a un bout de code spécifique qui masque les rooms DM avec les externes si le `directUserId` de ces rooms est un email (et non un Matrix ID).

Lorsqu'un utilisateur externe est invité sur Tchap, son user ID est son email.

Lorsqu'un utilisateur externe rejoint Tchap, son user ID devient un Matrix ID.

Dans le cas qui nous intéresse, si une room DM comporte encore un user ID d'externe au format email, c'est que cet externe n'a pas encore accepté l'invitation.

A partir de là, lui envoyer un message serait inutile car s'il n'a pas encore rejoint Tchap, il n'a pas de clés de chiffrement, et tout message envoyé sera définitivement chiffré pour lui.

Donc ce filtrage sert ou a servi à éviter que les premiers messages d'une room DM soient chiffrés à jamais.

Depuis, il y a eu d'autres travaux d'effectuer au niveau UI pour empêcher la saisie de message dans une room DM "non prête". Ce filtrage est donc peut-être devenu inutile.

Ce filtrage n'est pas présent sur Android ou web.

## Problème constaté ##

En pre-prod, le back-end ne remplace pas le user ID de l'invité par un Matrix ID quand l'invité rejoint Tchap.

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/16026093-4bb1-4036-912a-f21ab32629c6)

En prod, le user ID semble être remplacé par un Matrix ID (testé par Yoan).

## A vérifier ##
- la prod et la pre-pro sont-elles ISO fonctionnellement à ce sujet ?
- vérifier sur iOS si, en supprimant le filtrage, on peut donc voir et entrer dans un salon DM "non prêt", mais que la saisie de message est impossible.

Si ce dernier point d'avère vrai, alors il suffira dans un premier temps de supprimer le filtrage sur iOS.

**Comment by NicolasBuquet** [comment]
Voici le cheminement d'écran lors de l'invitation d'un externe sous Tchap iOS 2.4.7.

![dm-externe](https://github.com/tchapgouv/tchap-ios/assets/18608158/ea463bed-08ea-4521-b680-2c2b962d6719)

Ecran 1 : 
- tant que l'externe n'a pas créé de compte sur Tchap, le salon présente l'entête d'attente du correspondant et ne présente pas de zone de saisie en bas d'écran

Ecran 2 : 
- l'externe a créé son compte sur Tchap et l'a donc validé par le lien reçu dans l'email de confirmation. Il a donc un Matrix ID (affiché à la place de l'email dans cet écran). Les échanges peuvent donc être chiffrés. Le salon ne présente plus l'entête d'attente du correspondant et affiche la zone de saisie en bas d'écran

Ecran 3 : 
- l'externe a accepté l'invitation et a rejoint le salon DM. Son matrix ID a été remplacé par son email.

Cela signifie que l'on peut retirer le filtrage d'affichage de salon DM externe en attente sur la liste principale des salon, car même si on rentre dans ce salon, si l'externe n'a pas créé son compte, la zone de saisie sera absente, et aucun message ne pourra lui être envoyé (et donc rester définitivement chiffré).
