### ISSUE TITLE
iOS : Activer/desactiver les notifications email

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-ios#882]
Y a t il un bouton/switch à afficher?

**Comment by NicolasBuquet** [comment]
La fonctionnalité semble prise en charge directement par Element sur Android. (https://github.com/tchapgouv/tchap-android/issues/971)

L'équivalent n'a pas l'air d'exister sur iOS dans la Matrix SDK.

C'est donc plus long à intégrer, car ce sera une modification au niveau Matrix SDK entre autre.
