### ISSUE TITLE
Pas d'invite de login/password dans Btchap

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-ios#914]
#### Describe the bug.
Je voulais reproduire un bug, donc je me suis logout de l'appli iOs pour me reconnecter à un autre compte.

#### Steps to reproduce:
- je me deconnecte
- j'ai ré-installé l'app,
-  je tente de me login
- je vois un écran "contents de vous retrouver" avec un bouton connexion
- aucune saisie de mot de passe ne m'est proposé
- l'application est dans un état incohérent voir screenshot

#### Screenshots

![IMG_0783](https://github.com/tchapgouv/tchap-ios/assets/4077729/a3cbb55d-4eba-46a4-b3a3-a6f8e12b4d9c)
![IMG_0784](https://github.com/tchapgouv/tchap-ios/assets/4077729/c63de7ed-1afc-4877-8b74-490f0bd4541b)

#### Contextual information:

 - Device: 
 - OS: 

 - App Version:

**Comment by NicolasBuquet** [comment]
Problème dû à l'indisponibilité temporaire du back-end Pre-prod.
