### ISSUE TITLE
Inciter l'activation de la sauvegarde automatique

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#915]
Mettre en place un mécanisme qui permette d'inciter l'utilisateur à activer la sauvegarde automatique des clés de chiffrement des message (le key Backup).

Pour pouvoir activer cette sauvegarde automatique, il faut que l'appareil est activé le cross-signing et qu'il soit vérifié.

Une clé de paramétrage existe dans le fichier back-end well-known de configuration qui permet d'amorcer le processus. Cette clé est `secure_backup_required`.

Le well-known étant vide actuellement sur Tchap, on va forcé cette valeur à `TRUE` dans ls clients.

Le code existant, appelé dans `LegacyAppDelegate->handleAppState` est le suivant : 
```
        if (mainSession.vc_homeserverConfiguration.encryption.isSecureBackupRequired
            && mainSession.state == MXSessionStateRunning
            && mainSession.vc_canSetupSecureBackup)
        {
            // This only happens at the first login
            // Or when migrating an existing user
            MXLogDebug(@"[AppDelegate] handleAppState: Force SSSS setup");
            [self presentSecureBackupSetupForSession:mainSession];
        }
```

Voici ce qu'il teste : 
- la première condition est le isSecureBackupRequired forcé à TRUE (ou récupéré via le well-known configuration).
- la seconde condition passe par différents états au cours du démarrage (ready, inProgress puis Running je crois)
- la dernière condition vérifie si les clés nécessaires au cross-signing sont présentes localement

Si toutes c es conditions sont vérifiées, l'application affiche alors l'écran d'activation de la sauvegarde automatique (keyBackup) : 
![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/341f315c-c097-433e-8572-6fbfa6e92ec2)

La méthode `canSetupSecureBackup` est la suivante : 
```
- (BOOL)vc_canSetupSecureBackup
{
    MXRecoveryService *recoveryService = self.crypto.recoveryService;
    
    if (recoveryService.hasRecovery)
    {
        // Can't create secure backup if SSSS has already been set.
        return NO;
    }
    
    // Accept to create a setup only if we have the 3 cross-signing keys
    // This is the path to have a sane state
    // TODO: What about missing MSK that was not gossiped before?
    NSArray *crossSigningServiceSecrets = @[
                                            MXSecretId.crossSigningMaster,
                                            MXSecretId.crossSigningSelfSigning,
                                            MXSecretId.crossSigningUserSigning];
    
    return ([recoveryService.secretsStoredLocally mx_intersectArray:crossSigningServiceSecrets].count
            == crossSigningServiceSecrets.count);
}
```

Elle vérifie si les clé nécessaire au cross-signing sont présentes localement dans le SecureStorage.

Il faudra donc vérifier cela en amont, et seulement si ce n'est pas le cas, lancer l'activation du cross-signing (qui ne doit pas nécessiter l'intervention de l'utilisateur). Voir les classes `CrossSigningService` et `CrossSigningSetupCoordinator`.

Une fois assuré que le cross-signing est activé, alors on lancera l'activation de sauvegarde automatique : `[self presentSecureBackupSetupForSession:mainSession]`

**Comment by odelcroi** [comment]
pour cette premiere itération : se concentrer sur les utilisateurs dont l'activation de la sauv automatique est triviale : 
- pas de cross signing => on ne fait rien
- si cross signing activé sur ce compte et cet appareil (ios) est vérifié => on propose d'activer la sauv auto
- si cross activé sur le compte et cet appareil n'est pas vérifié => ?

en deuxieme itération : 
- pas de cross signing => l'activer pour l'utilisateur et le secure backup

**Comment by NicolasBuquet** [comment]
Test rapide effectué avec 2 appareils connectés au même compte.

Cross-signinig et sauvegarde automatique activée depuis l'iPhone.

- Création d'un salon.
- l'iPhone poste 2 messages
- le web poste 1 message
- déconnexion du web
- l'iPhone poste un 4e message
- déconnexion de l'iPhone
- reconnexion de l'iPhone
- demande du code de récupération sur l'iPhone (et uniquement cette solution)
- saisie acceptée du code de récupération
- tous les messages sont récupérés (jusqu'au 4e)
- connection depuis le web
- demande du code de récupération ou de vérification par un autre apapreil
- saisie acceptée du code de récupération
- tous les messages sont récupérés (jusqu'au 4e)

**Comment by NicolasBuquet** [comment]
@areox-net 

Voici l'écran à worder : 

![Simulator Screenshot - iPhone 15 - 2023-11-20 at 15 05 04](https://github.com/tchapgouv/tchap-ios/assets/18608158/209ca2e7-9c85-4e1c-8ad0-7ccc9bc8a031)

**Comment by NicolasBuquet** [comment]
@areox-net 

Et c'est autre écran, seconde partie au-dessus du bouton "Annuler" : 

![Simulator Screenshot - iPhone 15 - 2023-11-20 at 15 24 09](https://github.com/tchapgouv/tchap-ios/assets/18608158/a73bcf3b-fd28-42e8-8325-137a52524399)

**Comment by areox-net** [comment]
Voici les wording. 
Sinon, concernant l'UX, je ne suis pas fan du 2e écran. On a d'autre moments ou l'on parle aux users de l'activation de la signature croisée? J'ai peur qu'on les perde davantage avec ce texte. 
On avait parlé de mettre un bouton qui renvoit directement vers la signature croisée. On laisse ça pour une deuxième itération, c'est ça?


### 1er écran:

**Sauvegarde automatique des messages**
_Activez cette fonction pour ne jamais perdre l’accès à vos messages suite à une déconnexion._
Annuler  -  Activer

_______

### 2e écran
Si vous n'avez accès au aucun autre appareil, vous pouvez essayer d'activer la signature croisée dans vos paramètres.

**Comment by NicolasBuquet** [comment]
@areox-net Oui, pour le 2e écran, je mettrai un bouton qui envoie aux settings de sécurité un peu plu tard.

Merci pour les autres wording.

**Comment by NicolasBuquet** [comment]
@areox-net 

Done

![Simulator Screenshot - iPhone 15 - 2023-11-21 at 15 02 44](https://github.com/tchapgouv/tchap-ios/assets/18608158/e974c85f-2c18-47ef-9303-ad36c172c7a0)
