### ISSUE TITLE
la FAQ de chiffrement n'est pas à jour

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-ios#923]
La FAQ qui est lié lors d'une erreur de chiffrement n'est pas à jour : 
https://aide.tchap.beta.gouv.fr/fr/article/dechiffrement-impossible-de-mes-messages-comment-y-remedier-iphone-xotgv1

screenshot pas à jour
![image](https://github.com/tchapgouv/tchap-ios/assets/4077729/0b01b5db-413f-438b-8253-0b4577700c37)

alternative : 
renvoyer vers la page commune : 
https://aide.tchap.beta.gouv.fr/fr/article/messages-verrouilles-comment-les-recuperer-atnp15/

**Comment by NicolasBuquet** [comment]
Done
