### ISSUE TITLE
Code de récupération refusé

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#951]
Il arrive que l'application iOS refuse un code de récupération alors que celui-ci vient d'être généré par le client web par exemple.

Le message d'erreur présenté est générique : "Une erreur est survenue."

En fait, le code saisie par l'utilisateur est comparé au code du compte (de façon simplifiée) et les 2 codes ne correspondent pas.

⚠️  **C'est très gênant vu que l'on se dirige vers l'usage du code de récupération exclusivement sur Tchap pour vérifier les devices et récupérer les historiques de messages**. ⚠️ 

### La fonction de comparaison est dans le Matrix-sdk : 

```
func validPrivateKey(forRecoveryKey recoveryKey: String, for keyBackupVersion: MXKeyBackupVersion) throws -> Data {
        let key = try BackupRecoveryKey.fromBase58(key: recoveryKey)
        guard key.megolmV1PublicKey().publicKey == publicKey(for: keyBackupVersion) else {
            throw Error.invalidPrivateKey
        }
        
        let privateKey = try MXRecoveryKey.decode(recoveryKey)
        log.debug("Created valid private key from recovery key")
        return privateKey
    }
```

### Exemple de données de compte : 
```
Printing description of JSONDictionary:
{
    algorithm = "m.megolm_backup.v1.curve25519-aes-sha2";
    "auth_data" =     {
        "public_key" = qUqwkb21yIJbeconn6wPivnpydHMBhnbHNV8QWyxrwY;
        signatures =         {
            "@xxxxx.yyyyyyy-beta.gouv.fr:agent.dinum.tchap.gouv.fr" =             {
                "ed25519:YPJAZRHKVW" = "xexoRSskmVDb4HT0did...G1wXsOzas6R7LfNzLA/eU44UdxgNQZHah9w2sborqf/+GBw";
                "ed25519:r5lpLNTV+66IGMBbJFKk2uJGmmmkHP7Zo1oedzyBzfM" = "Mx6SdshgOm+zlYn0RITvXjR1ku...T0r4B0VoSG33Ut5sF7lDFRKaATTS1XNBmWPUNiErlICg";
            };
        };
    };
    count = 8934;
    etag = 45;
    version = 30;
}
```

### Exemple de résultat des fonctions de comparaison : 
```
recoveryKey.megolmV1PublicKey().publicKey
    [MXCryptoSDK] DEBUG matrix_sdk_crypto_ffi::backup_recovery_key: megolm_v1_public_key
    "yE6IkfNFJT8wltlLtn/w7zXPSLSGLVFl/wFEgHi2KXQ"

key.megolmV1PublicKey().publicKey
    [MXCryptoSDK] DEBUG matrix_sdk_crypto_ffi::backup_recovery_key: megolm_v1_public_key
    "5IvnKhpDt4e/diKoGSU7Vc2rAiNmZHtFXJvX0wh1iFU"
```

Cette partie de code se déclenche donc à la comparaison : 
```
guard key.megolmV1PublicKey().publicKey == publicKey(for: keyBackupVersion) else {
    throw Error.invalidPrivateKey
}        
```

Malgré les tentatives suivantes, le code de récupération saisi est toujours refusé : 
- refresh manuel sur la liste des salons
- vidage du cache

🌟🌟🌟 Une solution existe : se délogguer et se relogguer ! 🌟🌟🌟

### Supposition
L'application ne rafraîchit le code de récupération que lors du login.

C'est un bug présent chez Element.

J'ai ouvert un ticket chez eux : https://github.com/element-hq/element-ios/issues/7737

### Vidéo de présentation du bug : 

https://github.com/tchapgouv/tchap-ios/assets/18608158/e61789b7-4901-426c-8687-3e56dd3bc4dc

**Comment by odelcroi** [comment]
Il faudrait écrire une FAQ pour décrire le problème et proposer le workaround
