### ISSUE TITLE
VoIP l'application doit être en premier plan pour afficher l'UI CallKit d'un appel entrant

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#952]
Les notifications d'appel entrant arrivent chiffrées sur l'appareil car le backend ne sait pas les déchiffrer (c'est normal).

Tant que Apple n'autorise pas le Notification Filtering pour Tchap (https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_developer_usernotifications_filtering), la notification arrive comme une notification normale, non taggée `voip` et apparaît donc comme une notification normale.

Quand l'application est en arrière-plan ou non lancée, c'est l'application compagnon `Notification Service Extension` qui reçoit la notification et l'affiche classiquement sans appeler l'UI CallKit car elle ne sait pas que c'est une notification `voip`.

Si l'application est lancée, elle reçoit la notification, la déchiffre, voit que c'est une notification `voip` et peut donc invoquer l'UI CallKit.

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/64074c25-de0a-4036-afa8-327c253f8bf5)

**Comment by odelcroi** [comment]
Dû à ce ticket et au fait que Sygnal n'est pas exposé à l'extérieur en PROD.
L'appli recevant une notif chiffrée :

- elle la déchiffre
- elle voit que c'est du voip entrant 
- en mode legacy, elle fait une requête à Sygnal pour lui demander de renvoyer une notif en clair tagguée voip
Mais comme Sygnal n'est pas joignable en PROD (au contraire de DEV), l'appel Sygnal échoue et l'appel entrant voip ne peut être affiché.

La demande à Apple de Notification Filtering solutionnera ce problème.

**Comment by NicolasBuquet** [comment]
C'est le même problème et la même solution que pour le ticket #953 

L'obtention de l'entitlement de Notification Filtering de la part d'Apple solutionnera le problème, permettant de faire remonter les notifications taggées VOIP directement de l'extension d'app à l'application principale.

**Comment by NicolasBuquet** [comment]
Voir l'explication de Apple : https://developer.apple.com/documentation/callkit/sending_end-to-end_encrypted_voip_calls

**Comment by NicolasBuquet** [comment]
Fixed by #968
