### ISSUE TITLE
VoIP durant un appel si l'application passe en veille le son se coupe

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#953]
Actuellement, si durant un appel VoIP, l'application passe en veille, la capture et l'acheminement du son se coupe.

Réveiller l'application réactive l'acheminement du son dans les 2 sens.

La communication VoIP n'est donc pas coupée.

**Comment by NicolasBuquet** [comment]
Vérifier le bon fonctionnement de cette partie de code de `MXKCallViewController` :
```
- (void)updateProximityAndSleep
 {
     BOOL inCall = (mxCall.state == MXCallStateConnected || mxCall.state == MXCallStateRinging || mxCall.state == MXCallStateInviteSent || mxCall.state == MXCallStateConnecting || mxCall.state == MXCallStateCreateOffer || mxCall.state == MXCallStateCreateAnswer);

     BOOL isBuiltInReceiverUsed = self.isBuiltInReceiverAudioOuput;
     
     // Enable the proximity monitoring when the built in receiver is used as the audio output.
     BOOL enableProxMonitoring = inCall && isBuiltInReceiverUsed;
     
     UIDevice *device = [UIDevice currentDevice];
     if (device && device.isProximityMonitoringEnabled != enableProxMonitoring)
     {
         [device setProximityMonitoringEnabled:enableProxMonitoring];
     }

     // Disable the idle timer during a video call, or during a voice call which is performed with the built-in receiver.
     // Note: if the device is locked, VoIP calling get dropped if an incoming GSM call is received.
     BOOL disableIdleTimer = inCall && (mxCall.isVideoCall || isBuiltInReceiverUsed);
     
     UIApplication *sharedApplication = [UIApplication performSelector:@selector(sharedApplication)];
     if (sharedApplication && sharedApplication.isIdleTimerDisabled != disableIdleTimer)
     {
         sharedApplication.idleTimerDisabled = disableIdleTimer;
     }
 }
 ```

**Comment by NicolasBuquet** [comment]
Si l'application passe en background, le son se coupe aussi.

Voici le log à ce moment : 
```
[AppDelegate] applicationWillResignActive
[PushNotificationService] setShouldReceiveVoIPPushes: 1
[UNUserNotificationCenter] removeUnwantedNotifications: Removing 0 notifications.
[UNUserNotificationCenter] removeCallNotifications: Removing 0 notifications.
[PushNotificationService] configurePushKit
[AppDelegate] applicationDidEnterBackground
```

Quand l'application est en premier-plan, c'est elle qui reçoit directement les notifications chiffrées VoIP qu'elle peut déchiffrer et acheminer à l'audio.

Quand l'application est en arrière-plan, c'est l'extension qui reçoit les notifications chiffrées VoIP et qui devraient les déchiffrer puis redemander au serveur Sygnal de lui renvoyer en tant que Notification VoIP non chiffrée.

Quand Tchap aura l'autorisation de Notification Filtering, ces notifications chiffrées pourront être déchiffrées et routées directement à l'application qui pourra alors l'acheminer à l'audio. la VoIP ne devrait donc plus s'interrompre à mon avis.

A valider.

**Comment by yostyle** [comment]
ajouter un notion avec les infos de contacts

**Comment by julie-ri** [comment]
https://www.notion.so/mercurial-timer-ec4/Contact-APPLE-a1093484eab349c2973cd663a2ef98e3?pvs=4

**Comment by odelcroi** [comment]
> A valider (entre autre en testant la fonctionnalité sous Element).

@NicolasBuquet  est ce que ce comportement est le même en DEV avec le sygnal exposé?

**Comment by odelcroi** [comment]
Est ce qu'on a fait les démarches pour la preprod? @pseudonyme21 @mcalinghee

**Comment by NicolasBuquet** [comment]
@odelcroi Une fois le serveur Sygnal exposé sur DEV, l'application affiche correctement l'UI CallKit qu'elle soit lancée ou non.

Certaines notifications parasitent un peu l'affichage, mais le CallKit fonctionne.



![Image](https://github.com/tchapgouv/tchap-ios/assets/18608158/1265b5a4-a67b-4eed-b25c-863d3d3f3667)
![Image](https://github.com/tchapgouv/tchap-ios/assets/18608158/9180ee9c-446f-4529-aea5-7af53a1d146e)

**Comment by NicolasBuquet** [comment]
Fixed by #968
