### ISSUE TITLE
VoIP call si j'appuie sur le bouton on-off de l'iPhone, l'appel se coupe

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#971]
Si, pendant un appel VoIP, on appuie sur le bouton on/off de l'iPhone, l'appel se coupe.

Il est même noté "Appel refusé" du côté de l'iPhone faisant la manipulation.

Bug ou fonctionnalité ?

**Comment by odelcroi** [comment]
-> à tester avec les autres applis de messagerie comme whatsapp et signal

**Comment by NicolasBuquet** [comment]
@odelcroi 
Comportement non reproduit ce jour.

Tests à faire de manière plus large (tests DINUM ?)

**Comment by NicolasBuquet** [comment]
Reproduit ce jour sous Tchap 2.7.7 et iOS 17.3

Après avoir décroché et pris l'appel sur iPhone, appuyer sur le bouton on/off met fin à l'appel.

L'appel est indiqué comme "Terminé".

Cela arrive que l'on prenne l'appel depuis l'UI CallKit sans entrer dans Tchap, ou depuis l'UI de Tchap si l'application est active.

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/3839ec0a-74ca-46a6-ae8c-e13eb206035c)

A faire : tester le comportement sur Signal.

**Comment by NicolasBuquet** [comment]
Le comportement est le même sur Signal : un appui sur le bouton on/off de l'iPhone durant un appel VoIP met fin à l'appel.

Ce n'est pas propre à Tchap. C'est une fonctionnalité de Callkit :
- https://discussions.apple.com/thread/251105996?sortBy=best
- https://gadgetstouse.com/blog/2023/10/16/power-button-ends-call-iphone/
