### ISSUE TITLE
L'icone "signaler un probleme" est la meme que "rappeler"

### ISSUE THREAD

**Issue by odelcroi** [tchapgouv/tchap-ios#974]
![IMG_7FFF93BC30B4-1](https://github.com/tchapgouv/tchap-ios/assets/4077729/57415c73-db87-4159-b595-7d64e683b215)

**Comment by NicolasBuquet** [comment]
@odelcroi 
Quelques exemples d'icones de remplacement.

![bolt horizontal fill](https://github.com/tchapgouv/tchap-ios/assets/18608158/aa2a9207-dc95-4c97-9821-9e48af38dc14)
![speaker badge exclamationmark fill](https://github.com/tchapgouv/tchap-ios/assets/18608158/a1927b89-9c81-4e7a-9bfd-a09bca373d2e)
Celle que je vqis tester : ![exclamationmark bubble fill](https://github.com/tchapgouv/tchap-ios/assets/18608158/18e5b9e5-deed-4f79-81bd-b2b0d78ad0a1)
