### ISSUE TITLE
Changer le message d'erreur en cas de message non déchiffré

### ISSUE THREAD

**Issue by areox-net** [tchapgouv/tchap-ios#976]
Suite au dernières évolutions, nous allons faire un sorte que tous les clients affichent le meme message en cas de message non déchiffré:

![Screenshot 2024-02-26 at 15 04 55](https://github.com/tchapgouv/tchap-ios/assets/1255251/727f0b3d-c646-4c31-b374-28dea82ebafe)

Si possible, la couleur du message doit etre un gris #6A6A6A

**Comment by NicolasBuquet** [comment]
Sur iOS :

**Comment by areox-net** [comment]
Merci @NicolasBuquet On a pas de controle sur la largeur de la bulle? Ca serait top si on pouvez rester sur deux lignes.

**Comment by odelcroi** [comment]
On doit garder le "Patientez..." ? Ca parait redondant avec le "en cours" et ca prend pas mal de place. Qu'en penses-tu @areox-net ?

**Comment by areox-net** [comment]
@odelcroi Moi je milite toujours pour le moins de texte. Par contre ici on a introduit la notion d'attente pour dire que cela peu etre long.
Mais un "Déchiffrement en cours..." (avec les trois points) + "En savoir plus" ça pourrait suffir en effet

**Comment by NicolasBuquet** [comment]
> Merci @NicolasBuquet On a pas de controle sur la largeur de la bulle? Ca serait top si on pouvez rester sur deux lignes.

@areox-net Pas de contrôle sur la largeur de bulle.
Mais on pourrait écrire le message en typo plus petite éventuallement.

**Comment by NicolasBuquet** [comment]
@odelcroi 
J'ai enlevé le "Patientez…".
Il reste donc "Déchiffrement en cours…"

**Comment by areox-net** [comment]
@NicolasBuquet Tu aurais une prévu. On devrait rester sur 2 lignes maintenant, mais avec les points qui risquent d'aller déjà à la ligne peut-etre. 
Je ne sais pas s'il faut reduire la typo. Ca risque de faire bizarre. Si c'est 1 ou 2pt çà peut passer.

**Comment by NicolasBuquet** [comment]
@areox-net Capture sans changer la taille de typo
![Simulator Screenshot - iPhone 15 - 2024-03-05 at 11 26 50](https://github.com/tchapgouv/tchap-ios/assets/18608158/4cc7abb7-a2b5-4ff1-ac93-de2bd6fc75a0)

**Comment by NicolasBuquet** [comment]
Et sur iPhone 12 mini 

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/1e6ea5cc-f42f-4701-a7fa-4ac7abf4a1b7)

**Comment by areox-net** [comment]
@NicolasBuquet Super. On a besoin de garde la marge inferieure vue qu'il y a pas de timestamp?
