### ISSUE TITLE
Modifier le wording sur iOS pour indiquer la désactivation du compte

### ISSUE THREAD

**Issue by Delphgateau** [tchapgouv/tchap-ios#982]
Les utilisateurs qui souhaitent supprimer leur compte sont troublés par le wording "Désactiver le compte" dans la section Général des paramètres.
On pourrait s'aligner au client web en mettant "Fermer le compte" ?

**Comment by NicolasBuquet** [comment]
@areox-net 
Qu'en penses-tu ?

**Comment by areox-net** [comment]
@NicolasBuquet J'en ai discuté avec @Delphgateau au seminaire. "Fermer" me semble le bon terme car il faut plus définitif tout en gardant l'option de pouvoir le "reouvrir" si besoin.
