### ISSUE TITLE
[Geolocalisation] Impossible de partager sa geoloc en live pour un invité

### ISSUE THREAD

**Issue by NicolasBuquet** [tchapgouv/tchap-ios#984]
Un utilisateur ayant invité dans une DM un autre utilisateur, ce dernier ne peut pas partager sa géolocalisation pour cause de droit insuffisant dans la room.

En effet, le droit de l'utilisateur invité est au niveau 0, alors qu'il faut au moins être Modérateur (niveau 50) pour pouvoir partager sa position.

le créateur est niveau 100 (admin).

Pourquoi un utilisateur rejoingnat une DM n'est pas administrateur de cette DM lui aussi (niveau 100) ?

![image](https://github.com/tchapgouv/tchap-ios/assets/18608158/2f39bafa-99a6-4331-9f26-6185c9220e2f)

**Comment by NicolasBuquet** [comment]
Le code responsable de l'erreur : 

```
    // Check if user can send beacon info state event
    private func canShareLiveLocation() -> Bool {
        guard let myUserId = parameters.roomDataSource.mxSession.myUserId else {
            return false
        }
        
        let userPowerLevelRawValue = parameters.roomDataSource.roomState.powerLevels.powerLevelOfUser(withUserID: myUserId)
        
        guard let userPowerLevel = RoomPowerLevel(rawValue: userPowerLevelRawValue) else {
            return false
        }
        
        return userPowerLevel.rawValue >= RoomPowerLevel.moderator.rawValue
    }
```

**Comment by NicolasBuquet** [comment]
@mcalinghee @odelcroi 

Même bug de userLevel que ce ticket : https://github.com/tchapgouv/tchap-backend/issues/18 ?

**Comment by odelcroi** [comment]
C'est uniquement pour les partage de position en direct n'est ce pas?

**Comment by NicolasBuquet** [comment]
@odelcroi 
Oui, uniquement en live sharing.

**Comment by NicolasBuquet** [comment]
C'est un problème qui sera réglé par le back-end (niveau par défaut des users dans une DM).

**Comment by odelcroi** [comment]
tracké ici : https://github.com/tchapgouv/tchap-backend/issues/38

**Comment by NicolasBuquet** [comment]
Test geoloc effectué ce jour (16/05/2024) avec @yostyle et @MarcWadai : 

- DM : 
    - Android-iOS : ok
    - iOS-Android : ok
    - web-iOS : ok
    - iOS-web : ok
    - web-android : ok
    - android-web : ok

- Room nouvelle incluant le patch de @MatMaul à la création : 
    - web : ok
    - android: ok
    - iOS : ko (nécessite d'être Modérateur au moins - restriction code côté client iOS)

- Room d'avant patch Mathieu : 
    - web : ok
    - android: ok
    - iOS : ko (nécessite d'être Modérateur au moins - restriction code côté client iOS)

Le patch de @MatMaul fonctionne bien pour Android et web.

On va donc intégrer le patch iOS sur la non-vérification de droit minimum pour partager en temps réel sa géolocalisation.
